package gui;

import dao.DAOalbums;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Albums;

public class DlgAlbums extends javax.swing.JDialog {
    DefaultTableModel e,c;
    public DlgAlbums(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setResizable(false);
        initComponents();
        e = (DefaultTableModel)tblClienteE.getModel();
        c = (DefaultTableModel)tblClienteC.getModel();
        //BOTON AGREGAR
        ImageIcon icagre=new ImageIcon(getClass().getResource("/Imagenes/agregar.png"));
        Icon iconoagre=new ImageIcon(icagre.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnAgregar.setIcon(iconoagre);
        //BOTON ELIMINAR
        ImageIcon icelim=new ImageIcon(getClass().getResource("/Imagenes/eliminar.png"));
        Icon iconoelim=new ImageIcon(icelim.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnBuscarE.setIcon(iconoelim);
        //BOTON BUSCAR
        ImageIcon icbuscar=new ImageIcon(getClass().getResource("/Imagenes/buscar.png"));
        Icon iconobuscar=new ImageIcon(icbuscar.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnBuscar.setIcon(iconobuscar);
        //BOTON MODIFICAR
        ImageIcon icmodif=new ImageIcon(getClass().getResource("/Imagenes/edit.png"));
        Icon iconomodif=new ImageIcon(icmodif.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnModif.setIcon(iconomodif);
        //Deshabilitar botones
        btnAgregar.setEnabled(false);
        btnBuscarE.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnModif.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JTabbedPane();
        pnlAltas = new javax.swing.JPanel();
        lblAltIDCli = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIdGen = new javax.swing.JLabel();
        lblAltRFC = new javax.swing.JLabel();
        lblAltExp = new javax.swing.JLabel();
        lblAltDur = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        lblCorr1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtAltIDAl = new javax.swing.JTextField();
        txtAltArt = new javax.swing.JTextField();
        txtAltNom = new javax.swing.JTextField();
        cmbEx = new javax.swing.JComboBox<>();
        txtAltDisc = new javax.swing.JTextField();
        txtAltFE = new javax.swing.JTextField();
        txtAltOy = new javax.swing.JTextField();
        pnlAv = new javax.swing.JPanel();
        lblAvisoIDAl = new javax.swing.JLabel();
        lblAvisoIdArt = new javax.swing.JLabel();
        lblAvisoNombre = new javax.swing.JLabel();
        lblAvisoExplicita = new javax.swing.JLabel();
        lblAvisoFE = new javax.swing.JLabel();
        lblAvisoDisc = new javax.swing.JLabel();
        lblAltOy = new javax.swing.JLabel();
        pnlBajas = new javax.swing.JPanel();
        lblBajID = new javax.swing.JLabel();
        txtBajID = new javax.swing.JTextField();
        btnBuscarE = new javax.swing.JButton();
        lblAvisoID2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClienteE = new javax.swing.JTable();
        btnEliminar1 = new javax.swing.JButton();
        pnlCambios = new javax.swing.JPanel();
        btnModif = new javax.swing.JButton();
        txtModCorr = new javax.swing.JTextField();
        lblCorr2 = new javax.swing.JLabel();
        txtModCont = new javax.swing.JTextField();
        btnBuscarM = new javax.swing.JButton();
        lblCamFE = new javax.swing.JLabel();
        lblCamDis = new javax.swing.JLabel();
        lblAltIDCli1 = new javax.swing.JLabel();
        lblCamIdArt = new javax.swing.JLabel();
        lblCamNom = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtCamIDA = new javax.swing.JTextField();
        txtCamNom = new javax.swing.JTextField();
        txtCamFE = new javax.swing.JTextField();
        cmbCamEx = new javax.swing.JComboBox<>();
        txtCamDisc = new javax.swing.JTextField();
        txtAltDur2 = new javax.swing.JTextField();
        txtCamIDG = new javax.swing.JTextField();
        lblCamExp = new javax.swing.JLabel();
        lblCamOy = new javax.swing.JLabel();
        lblAvisoRFC2 = new javax.swing.JLabel();
        lblAvisoIDC2 = new javax.swing.JLabel();
        pnlAv1 = new javax.swing.JPanel();
        lblAvisoIDC1 = new javax.swing.JLabel();
        lblAvisoIdArt1 = new javax.swing.JLabel();
        lblAvisoNombre1 = new javax.swing.JLabel();
        lblAvisoExplicita1 = new javax.swing.JLabel();
        lblAvisoFE1 = new javax.swing.JLabel();
        lblAvisoDisc1 = new javax.swing.JLabel();
        pnlConsultas = new javax.swing.JPanel();
        lblConsIdCan = new javax.swing.JLabel();
        txtConIDCan = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblAvisoID3 = new javax.swing.JLabel();
        btnBuscarTds = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClienteC = new javax.swing.JTable();
        pnlReportes = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ALBUMS");

        pnlPrincipal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblAltIDCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltIDCli.setText("ID Album:");

        lblIdGen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdGen.setText("ID Artista:");

        lblAltRFC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltRFC.setText("Nombre");

        lblAltExp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltExp.setText("Explicita");

        lblAltDur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltDur.setText("Fecha Estreno");

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblCorr1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCorr1.setText("Discografia");

        txtAltIDAl.setEditable(false);
        txtAltIDAl.setText("0");
        txtAltIDAl.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltIDAl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltIDAlKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltIDAlKeyTyped(evt);
            }
        });

        txtAltArt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltArt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltArtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltArtKeyTyped(evt);
            }
        });

        txtAltNom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltNomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltNomKeyTyped(evt);
            }
        });

        cmbEx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbEx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "SI", "NO" }));

        txtAltDisc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltDiscActionPerformed(evt);
            }
        });
        txtAltDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltDiscKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltDiscKeyTyped(evt);
            }
        });

        txtAltFE.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltFEActionPerformed(evt);
            }
        });
        txtAltFE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltFEKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltFEKeyTyped(evt);
            }
        });

        txtAltOy.setEditable(false);
        txtAltOy.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltOy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltOyActionPerformed(evt);
            }
        });
        txtAltOy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltOyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltOyKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAltOy, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtAltIDAl, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAltArt, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbEx, javax.swing.GroupLayout.Alignment.LEADING, 0, 131, Short.MAX_VALUE)
                    .addComponent(txtAltNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAltDisc, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAltFE, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtAltIDAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtAltFE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(txtAltOy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        lblAvisoIDAl.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDAl.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoIdArt.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIdArt.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoNombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoNombre.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoExplicita.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoExplicita.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoFE.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoFE.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoDisc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoDisc.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlAvLayout = new javax.swing.GroupLayout(pnlAv);
        pnlAv.setLayout(pnlAvLayout);
        pnlAvLayout.setHorizontalGroup(
            pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvisoIDAl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoExplicita, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoFE, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAvLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblAvisoIdArt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        pnlAvLayout.setVerticalGroup(
            pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvLayout.createSequentialGroup()
                .addComponent(lblAvisoIDAl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblAvisoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(lblAvisoFE, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAvisoExplicita, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lblAvisoDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAvLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(lblAvisoIdArt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(206, Short.MAX_VALUE)))
        );

        lblAltOy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltOy.setText("Oyentes");

        javax.swing.GroupLayout pnlAltasLayout = new javax.swing.GroupLayout(pnlAltas);
        pnlAltas.setLayout(pnlAltasLayout);
        pnlAltasLayout.setHorizontalGroup(
            pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAltRFC)
                    .addComponent(lblAltExp)
                    .addComponent(lblAltDur)
                    .addComponent(lblAltOy)
                    .addComponent(lblCorr1)
                    .addGroup(pnlAltasLayout.createSequentialGroup()
                        .addComponent(lblIdGen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(lblAltIDCli))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pnlAv, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAltasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(199, 199, 199))
        );
        pnlAltasLayout.setVerticalGroup(
            pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAltasLayout.createSequentialGroup()
                        .addComponent(lblAltIDCli)
                        .addGap(9, 9, 9)
                        .addComponent(lblIdGen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblAltRFC)
                        .addGap(15, 15, 15)
                        .addComponent(lblAltDur)
                        .addGap(18, 18, 18)
                        .addComponent(lblAltExp)
                        .addGap(22, 22, 22)
                        .addComponent(lblAltOy)
                        .addGap(18, 18, 18)
                        .addComponent(lblCorr1))
                    .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addComponent(btnAgregar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("ALTAS", pnlAltas);

        lblBajID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBajID.setText("ID Album:");

        txtBajID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtBajID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBajIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBajIDKeyTyped(evt);
            }
        });

        btnBuscarE.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarE.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarE.setText("BUSCAR");
        btnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEActionPerformed(evt);
            }
        });

        lblAvisoID2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoID2.setForeground(new java.awt.Color(255, 0, 0));

        tblClienteE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Email", "Contraseña", "Razon Social", "RFC", "Domicilio", "CDFI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblClienteE);

        btnEliminar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.setEnabled(false);
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBajasLayout = new javax.swing.GroupLayout(pnlBajas);
        pnlBajas.setLayout(pnlBajasLayout);
        pnlBajasLayout.setHorizontalGroup(
            pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBajasLayout.createSequentialGroup()
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblBajID)
                        .addGap(46, 46, 46)
                        .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarE)
                            .addGroup(pnlBajasLayout.createSequentialGroup()
                                .addComponent(txtBajID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblAvisoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBajasLayout.createSequentialGroup()
                    .addGap(323, 323, 323)
                    .addComponent(btnEliminar1)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );
        pnlBajasLayout.setVerticalGroup(
            pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBajasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBajID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBajID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarE))
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblAvisoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBajasLayout.createSequentialGroup()
                    .addContainerGap(287, Short.MAX_VALUE)
                    .addComponent(btnEliminar1)
                    .addGap(56, 56, 56)))
        );

        pnlPrincipal.addTab("BAJAS", pnlBajas);

        btnModif.setBackground(new java.awt.Color(255, 255, 255));
        btnModif.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnModif.setText("MODIFICAR");
        btnModif.setEnabled(false);
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });

        txtModCorr.setEditable(false);
        txtModCorr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtModCorr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModCorrKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModCorrKeyTyped(evt);
            }
        });

        lblCorr2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCorr2.setText("Contraseña:");

        txtModCont.setEditable(false);
        txtModCont.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtModCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModContActionPerformed(evt);
            }
        });
        txtModCont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModContKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModContKeyTyped(evt);
            }
        });

        btnBuscarM.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarM.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarM.setText("BUSCAR");
        btnBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMActionPerformed(evt);
            }
        });

        lblCamFE.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamFE.setText("Fecha Estreno");

        lblCamDis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamDis.setText("Discografia");

        lblAltIDCli1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltIDCli1.setText("ID Album:");

        lblCamIdArt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamIdArt.setText("ID Artista:");

        lblCamNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamNom.setText("Nombre");

        txtCamIDA.setEditable(false);
        txtCamIDA.setText("0");
        txtCamIDA.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamIDA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamIDAKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamIDAKeyTyped(evt);
            }
        });

        txtCamNom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamNomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamNomKeyTyped(evt);
            }
        });

        txtCamFE.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamFE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamFEKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamFEKeyTyped(evt);
            }
        });

        cmbCamEx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbCamEx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "SI", "NO" }));

        txtCamDisc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamDiscActionPerformed(evt);
            }
        });
        txtCamDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamDiscKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamDiscKeyTyped(evt);
            }
        });

        txtAltDur2.setEditable(false);
        txtAltDur2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltDur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltDur2ActionPerformed(evt);
            }
        });
        txtAltDur2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltDur2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltDur2KeyTyped(evt);
            }
        });

        txtCamIDG.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamIDG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamIDGKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamIDGKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCamNom)
                    .addComponent(txtCamIDG, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtCamIDA)
                    .addComponent(cmbCamEx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAltDur2)
                    .addComponent(txtCamFE, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtCamDisc))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtCamIDA, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(txtCamIDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCamNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCamFE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbCamEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltDur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCamDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCamExp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamExp.setText("Explicita");

        lblCamOy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamOy.setText("Oyentes");

        lblAvisoRFC2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoRFC2.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoIDC2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDC2.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoIDC1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDC1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoIdArt1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIdArt1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoNombre1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoNombre1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoExplicita1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoExplicita1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoFE1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoFE1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoDisc1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoDisc1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlAv1Layout = new javax.swing.GroupLayout(pnlAv1);
        pnlAv1.setLayout(pnlAv1Layout);
        pnlAv1Layout.setHorizontalGroup(
            pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAv1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvisoIDC1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoExplicita1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoFE1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoDisc1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAv1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblAvisoIdArt1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        pnlAv1Layout.setVerticalGroup(
            pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAv1Layout.createSequentialGroup()
                .addComponent(lblAvisoIDC1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(lblAvisoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvisoFE1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(lblAvisoExplicita1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(lblAvisoDisc1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAv1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(lblAvisoIdArt1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(190, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlCambiosLayout = new javax.swing.GroupLayout(pnlCambios);
        pnlCambios.setLayout(pnlCambiosLayout);
        pnlCambiosLayout.setHorizontalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnModif))
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblCamExp)
                                .addGap(51, 51, 51))
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCamOy)
                                    .addComponent(lblCamDis)
                                    .addComponent(lblCamNom)
                                    .addComponent(lblCamIdArt)
                                    .addComponent(lblAltIDCli1)
                                    .addComponent(lblCamFE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarM)
                        .addGap(18, 18, 18)
                        .addComponent(pnlAv1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112)
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addComponent(lblAvisoIDC2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCorr2)
                        .addGap(48, 48, 48)
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModCorr, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModCont, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106))
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addComponent(lblAvisoRFC2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlCambiosLayout.setVerticalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addComponent(lblAltIDCli1)
                                .addGap(18, 18, 18)
                                .addComponent(lblCamIdArt)
                                .addGap(11, 11, 11)
                                .addComponent(lblCamNom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCamFE)
                                .addGap(25, 25, 25)
                                .addComponent(lblCamExp)
                                .addGap(18, 18, 18)
                                .addComponent(lblCamOy)
                                .addGap(18, 18, 18)
                                .addComponent(lblCamDis))
                            .addComponent(pnlAv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addComponent(btnModif))
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtModCorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBuscarM))
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(lblAvisoIDC2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorr2)
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtModCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47)
                        .addComponent(lblAvisoRFC2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("CAMBIOS", pnlCambios);

        lblConsIdCan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConsIdCan.setText("ID Album:");

        txtConIDCan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtConIDCan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConIDCanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConIDCanKeyTyped(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblAvisoID3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoID3.setForeground(new java.awt.Color(255, 0, 0));

        btnBuscarTds.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarTds.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarTds.setText("MOSTRAR TODOS");
        btnBuscarTds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTdsActionPerformed(evt);
            }
        });

        tblClienteC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Email", "Contraseña", "Razon Social", "RFC", "Domicilio", "CDFI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblClienteC);

        javax.swing.GroupLayout pnlConsultasLayout = new javax.swing.GroupLayout(pnlConsultas);
        pnlConsultas.setLayout(pnlConsultasLayout);
        pnlConsultasLayout.setHorizontalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblConsIdCan)
                        .addGap(45, 45, 45)
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConIDCan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlConsultasLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnBuscar)))
                        .addGap(73, 73, 73)
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarTds)
                            .addComponent(lblAvisoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConsultasLayout.setVerticalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConsIdCan)
                        .addComponent(txtConIDCan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAvisoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(btnBuscarTds))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("CONSULTAS", pnlConsultas);

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        pnlPrincipal.addTab("REPORTES", pnlReportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTdsActionPerformed
        /*Object clienteC[] = new Object[7];
        DAOclientes cliente = new DAOclientes();
        ArrayList<Clientes> clientes = null;
        while (c.getRowCount() > 0){
            c.removeRow(0);
        }
        if(c.getRowCount() == 0){
            try {
                clientes = cliente.select();
                for (Clientes clnt : clientes) {

                    clienteC[0] =  clnt.getIdCliente();
                    clienteC[1] =  clnt.getEmailCliente();
                    clienteC[2] =  clnt.getPasswordCliente();
                    clienteC[3] =  clnt.getRsCliente();
                    clienteC[4] =  clnt.getRfcCLiente();
                    clienteC[5] =  clnt.getDomicilioCliente();
                    clienteC[6] =  clnt.getCdfiCliente();

                    c.addRow(clienteC);
                }
            }
            catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
        }
        txtConIDCan.setText("");*/
    }//GEN-LAST:event_btnBuscarTdsActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        /*boolean encontrado = false;
        idBuscar = Integer.parseInt(txtConIDCan.getText());
        Object clienteM[] = new Object[7];
        DAOclientes cliente = new DAOclientes();
        ArrayList<Clientes> clientes = null;

        try {
            clientes = cliente.select();
            for (Clientes clnt : clientes) {
                if(clnt.getIdCliente() == idBuscar){

                    clienteM[0] =  clnt.getIdCliente();
                    clienteM[1] =  clnt.getEmailCliente();
                    clienteM[2] =  clnt.getPasswordCliente();
                    clienteM[3] =  clnt.getRsCliente();
                    clienteM[4] =  clnt.getRfcCLiente();
                    clienteM[5] =  clnt.getDomicilioCliente();
                    clienteM[6] =  clnt.getCdfiCliente();

                    encontrado = true;
                    break;
                }
            }
        }
        catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        if(encontrado){
            while (c.getRowCount() > 0){
                c.removeRow(0);
            }
            if(c.getRowCount() == 0)
            c.addRow(clienteM);
        }
        else{
            JOptionPane.showMessageDialog(this, "Empleado no encontrado");
        }*/
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtConIDCanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConIDCanKeyTyped
        //validarNumeros(evt);
    }//GEN-LAST:event_txtConIDCanKeyTyped

    private void txtConIDCanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConIDCanKeyReleased
        //habilitarBotonB();
        //validarVacios3();
    }//GEN-LAST:event_txtConIDCanKeyReleased

    private void btnBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMActionPerformed
        /*boolean clienteEncontrado = false;
        idModificar = Integer.parseInt(txtCamIDG.getText());
        Object clienteM[] = new Object[13];
        DAOclientes cliente = new DAOclientes();
        ArrayList<Clientes> clientes = null;

        try {
            clientes = cliente.select();
            for (Clientes clnt : clientes) {
                if(clnt.getIdCliente() == idModificar){
                    clienteM[0] =  clnt.getIdCliente();
                    clienteM[1] =  clnt.getEmailCliente();
                    clienteM[2] =  clnt.getPasswordCliente();
                    clienteM[3] =  clnt.getRsCliente();
                    clienteM[4] =  clnt.getRfcCLiente();
                    clienteM[5] =  clnt.getDomicilioCliente();
                    clienteM[6] =  clnt.getCdfiCliente();
                    clienteEncontrado = true;
                    break;
                }
            }
        }
        catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        if(clienteEncontrado){
            btnModif.setEnabled(true);
            habilitarCompMod();
            agrgarElementosModif(clienteM);
        }
        else
        JOptionPane.showMessageDialog(this, "Empleado no encontrado");*/
    }//GEN-LAST:event_btnBuscarMActionPerformed

    private void txtModContKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModContKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModContKeyTyped

    private void txtModContKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModContKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModContKeyReleased

    private void txtModContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModContActionPerformed

    private void txtModCorrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModCorrKeyTyped
        //validarCorreo(evt);
    }//GEN-LAST:event_txtModCorrKeyTyped

    private void txtModCorrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModCorrKeyReleased
        //habilitarBotonM();
        //validarVacios1();
    }//GEN-LAST:event_txtModCorrKeyReleased

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        /*empleadoModID = Integer.parseInt(txtCamIDG.getText());
        String clienteModEmail = txtModCorr.getText();
        String clienteModPass = txtModCont.getText();
        String clienteModRs = txtModRaz.getText();
        String clienteModRFC = txtModRFC.getText();
        String clienteModDom = txtModDom.getText();
        String cliadoModCdfi = CmbBxAltCFDICli1.getSelectedItem().toString();

        /*
        1.- Crear una instancia del objeto DAOClientes
        DAOEmpleados empleado = new DAOEmpleados();
        2.- Creamos un nuevo objeto de tipo Cliente
        Empleados empleadosU = new Empleados();
        //Agregamos el ID de la persona que deseamos modificar
        empleadoU.setIdCliente(1);
        empleadoU.setRsCliente("RS");
        //Seteamos los demas parametros
        3.- Ejecutamos
        empleado.update(empleadosU);//Devulve un entero si se aplico el UPDATE, exactamente un 1 porque
        //esa es la cantidad de registros que modifico
        */
        /*DAOclientes cliente = new DAOclientes();
        Clientes clienteU = new Clientes();
        clienteU.setIdCliente(empleadoModID);
        clienteU.setEmailCliente(clienteModEmail);
        clienteU.setPasswordCliente(clienteModPass);
        clienteU.setRsCliente(clienteModRs);
        clienteU.setRfcCLiente(clienteModRFC);
        clienteU.setDomicilioCliente(clienteModDom);
        clienteU.setCdfiCliente(cliadoModCdfi);
        try {
            if(cliente.update(clienteU) != 0){
                JOptionPane.showMessageDialog(this, "Empleado modificado con exito");
                deshabilitarCompMod();
            }
            else
            JOptionPane.showMessageDialog(this, "El empleado no se modifico");
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }*/
    }//GEN-LAST:event_btnModifActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        /*DELETE
        1.- Crear una instancia del objeto DAOEmpleados
        DAOempleados empleado = new DAOempleados();
        2.- Creamos un nuevo objeto de tipo Empleados
        Empleados empleadoD = new Empleados();
        3.- Agregamos al objeto persona el ID del empleado a eliminar
        empleadoD.setIdCliente(1);
        4.- Ejecutamos
        empleado.delete(empleadoD);//Devulve un entero si se aplico el DELETE, exactamente un 1 porque
        //esa es la cantidad de registros que elimino
        */
        /*if(idEliminar != 0){
            DAOclientes cliente = new DAOclientes();
            Clientes deleteCliente = new Clientes();
            deleteCliente.setIdCliente(idEliminar);
            try {
                if(cliente.delete(deleteCliente) != 0){
                    JOptionPane.showMessageDialog(this, "Cliente eliminado con exito");
                    txtBajID.setText("");
                    txtBajID.removeAll();
                }
                else
                JOptionPane.showMessageDialog(this, "Hubo un error al eliminar el cliente");
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
        }
        while (e.getRowCount() > 0){
            e.removeRow(0);
        }*/
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEActionPerformed
        /*boolean clienteEncontrado = false;
        idEliminar = Integer.parseInt(txtBajID.getText());
        Object clienteE[] = new Object[7];
        DAOclientes cliente = new DAOclientes();
        ArrayList<Clientes> clientess = null;

        try {
            clientess = cliente.select();
            for (Clientes clnt : clientess) {
                if(clnt.getIdCliente()== idEliminar){
                    clienteE[0] =  clnt.getIdCliente();
                    clienteE[1] =  clnt.getEmailCliente();
                    clienteE[2] =  clnt.getPasswordCliente();
                    clienteE[3] =  clnt.getRsCliente();
                    clienteE[4] =  clnt.getRfcCLiente();
                    clienteE[5] =  clnt.getDomicilioCliente();
                    clienteE[6] =  clnt.getCdfiCliente();
                    clienteEncontrado = true;
                    break;
                }
            }
        }
        catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        while (e.getRowCount() > 0){
            e.removeRow(0);
        }
        if(clienteEncontrado){

            if(e.getRowCount() == 0){
                e.addRow(clienteE);
                btnEliminar1.setEnabled(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Cliente no encontrado");
        }*/
    }//GEN-LAST:event_btnBuscarEActionPerformed

    private void txtBajIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBajIDKeyTyped
        //validarNumeros(evt);
    }//GEN-LAST:event_txtBajIDKeyTyped

    private void txtBajIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBajIDKeyReleased
        /*habilitarBotonE();
        validarVacios2();*/
    }//GEN-LAST:event_txtBajIDKeyReleased

    private void txtAltFEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltFEKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltFEKeyTyped

    private void txtAltFEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltFEKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltFEKeyReleased

    private void txtAltFEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltFEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltFEActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        /*String emailCliente = txtAltCorrC.getText();
        String passwordCliente = txtAltDur.getText();
        String rsCliente = txtAltRaz.getText();
        String rfcCLiente = txtAltRFCC.getText();
        String domicilioCliente = txtAltDom.getText();
        String cdfiCliente = CmbBxAltCFDICli.getSelectedItem().toString();

        //        emailCliente,passwordCliente,rsCliente,rfcCLiente,domicilioCliente,cdfiCliente

        insertarCliente(emailCliente,passwordCliente,rsCliente,rfcCLiente,domicilioCliente,cdfiCliente);*/
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtAltDiscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltDiscKeyTyped
        //validarCorreo(evt);
    }//GEN-LAST:event_txtAltDiscKeyTyped

    private void txtAltDiscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltDiscKeyReleased
        /*habilitarBoton();
        validarVacios();*/
    }//GEN-LAST:event_txtAltDiscKeyReleased

    private void txtAltDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltDiscActionPerformed

    private void txtAltNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltNomKeyTyped
       // validarRFC(evt);
    }//GEN-LAST:event_txtAltNomKeyTyped

    private void txtAltNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltNomKeyReleased
       /* habilitarBoton();
        validarVacios();*/
    }//GEN-LAST:event_txtAltNomKeyReleased

    private void txtAltArtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltArtKeyTyped
        //validarCaracter(evt);
    }//GEN-LAST:event_txtAltArtKeyTyped

    private void txtAltArtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltArtKeyReleased
        /*habilitarBoton();
        validarVacios();*/
    }//GEN-LAST:event_txtAltArtKeyReleased

    private void txtAltIDAlKeyReleased(java.awt.event.KeyEvent evt) {                                   
       // validarNumeros(evt);
    }  
    private void txtAltIDAlKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltIDAlKeyTyped
       // validarNumeros(evt);
    }//GEN-LAST:event_txtAltIDAlKeyTyped

//GEN-FIRST:event_txtAltIDCKeyReleased
 
//GEN-LAST:event_txtAltIDCKeyReleased

    private void txtAltOyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltOyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltOyActionPerformed

    private void txtAltOyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltOyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltOyKeyReleased

    private void txtAltOyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltOyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltOyKeyTyped

    private void txtCamIDAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDAKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamIDAKeyReleased

    private void txtCamIDAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDAKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamIDAKeyTyped

    private void txtCamNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamNomKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamNomKeyReleased

    private void txtCamNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamNomKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamNomKeyTyped

    private void txtCamFEKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamFEKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamFEKeyReleased

    private void txtCamFEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamFEKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamFEKeyTyped

    private void txtCamDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamDiscActionPerformed

    private void txtCamDiscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamDiscKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamDiscKeyReleased

    private void txtCamDiscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamDiscKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamDiscKeyTyped

    private void txtAltDur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltDur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltDur2ActionPerformed

    private void txtAltDur2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltDur2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltDur2KeyReleased

    private void txtAltDur2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltDur2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltDur2KeyTyped

    private void txtCamIDGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDGKeyTyped
        //validarNumeros(evt);
    }//GEN-LAST:event_txtCamIDGKeyTyped

    private void txtCamIDGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDGKeyReleased
        /*habilitarBotonM();
        validarVacios1();*/
    }//GEN-LAST:event_txtCamIDGKeyReleased

   
     /*public void validarVacios(){
        if(txtAltIDC.getText().isEmpty()){
            lblAvisoIDC.setText("Campo obligatorio");
        }else{
            lblAvisoIDC.setText("");
        }
        if(txtAltRaz.getText().isEmpty()){
            lblAvisoIdGen.setText("Campo obligatorio");
        }else{
            lblAvisoIdGen.setText("");
        }
        if(txtAltRFCC.getText().isEmpty()){
            lblAvisoRFC.setText("Campo obligatorio");
        }else{
            lblAvisoRFC.setText("");
        }
        if(txtAltDom.getText().isEmpty()){
            lblAvisoDom.setText("Campo obligatorio");
        }else{
            lblAvisoDom.setText("");
        }
        if(txtAltCorrC.getText().isEmpty()){
            lblAvisoCorr.setText("Campo obligatorio");
        }else 
            if(!txtAltCorrC.getText().contains("@")
                  ||!txtAltCorrC.getText().contains(".")){
                lblAvisoCorr.setText("Correo NO valido");
            }else{
                lblAvisoCorr.setText("");
            }
        if(txtAltDur.getText().isEmpty()){
            lblAvisoNombre.setText("Campo obligatorio");
        }else{
            lblAvisoNombre.setText("");
        }
    }
     
     public void validarVacios1(){
        if(txtCamIDG.getText().isEmpty()){
            lblAvisoIDC1.setText("Campo obligatorio");
        }else{
            lblAvisoIDC1.setText("");
        }
        if(txtModRaz.getText().isEmpty()){
            lblAvisoRaz1.setText("Campo obligatorio");
        }else{
            lblAvisoRaz1.setText("");
        }
        if(txtModRFC.getText().isEmpty()){
            lblAvisoRFC1.setText("Campo obligatorio");
        }else{
            lblAvisoRFC1.setText("");
        }
        if(txtModDom.getText().isEmpty()){
            lblAvisoDom1.setText("Campo obligatorio");
        }else{
            lblAvisoDom1.setText("");
        }
        if(txtModCorr.getText().isEmpty()){
            lblAvisoCorr1.setText("Campo obligatorio");
        }else 
            if(!txtModCorr.getText().contains("@")
                  ||!txtModCorr.getText().contains(".")){
                lblAvisoCorr1.setText("Correo NO valido");
            }else{
                lblAvisoCorr1.setText("");
            }
        if(txtModCont.getText().isEmpty()){
            lblAvisoCont1.setText("Campo obligatorio");
        }else{
            lblAvisoCont1.setText("");
        }
    }
    public void validarVacios2(){
        if(txtBajID.getText().isEmpty()){
            lblAvisoID2.setText("ID obligatorio");
        }else{
            lblAvisoID2.setText("");
        }
    }
    
    public void validarVacios3(){
        if(txtConIDCan.getText().isEmpty()){
            lblAvisoID3.setText("ID obligatorio");
        }else{
            lblAvisoID3.setText("");
        }
    }
    
    public void validarCorreo(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()>=32 && evento.getKeyChar()<=44
                ||evento.getKeyChar()==47
                ||evento.getKeyChar()>=58 && evento.getKeyChar()<=63
                ||evento.getKeyChar()>=91 && evento.getKeyChar()<=94
                ||evento.getKeyChar()==96
                ||evento.getKeyChar()>=123 && evento.getKeyChar()<=255){
            evento.consume();
            JOptionPane.showMessageDialog(this,"No se permite este caracter");
        }
    }
    
    public void validarRFC(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()>=33 && evento.getKeyChar()<=47
                || evento.getKeyChar()>=58 && evento.getKeyChar()<=64
                || evento.getKeyChar()>=91 && evento.getKeyChar()<=255){
            evento.consume();
            JOptionPane.showMessageDialog(this,"Solo se permiten numeros y mayusculas");
        }
    }
    
    public void validarNumeros(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()>=32 && evento.getKeyChar()<=47
                ||evento.getKeyChar()>=58 && evento.getKeyChar()<=255){
            evento.consume();
            JOptionPane.showMessageDialog(this,"Solo Numeros");
        }
    }
    
    public void validarDomicilio(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()==33
                ||evento.getKeyChar()==34
                ||evento.getKeyChar()>=36 && evento.getKeyChar()<=43
                ||evento.getKeyChar()==45
                ||evento.getKeyChar()>=58 && evento.getKeyChar()<=64
                ||evento.getKeyChar()>=91 && evento.getKeyChar()<=96
                ||evento.getKeyChar()>=123 && evento.getKeyChar()<=255){
            evento.consume();
            JOptionPane.showMessageDialog(this,"No se permiten caracteres especiales");
        }
    }
    
    public void habilitarBoton(){
        if(txtAltIDC.getText().isEmpty() 
                || txtAltRaz.getText().isEmpty() 
                || txtAltRFCC.getText().isEmpty() 
                || txtAltDom.getText().isEmpty() 
                || txtAltCorrC.getText().isEmpty()
                || txtAltDur.getText().isEmpty()){
            btnAgregar.setEnabled(false);
        }else{
            btnAgregar.setEnabled(true);
        }
    }
    
    public void habilitarBotonM(){
        if(txtAltIDC.getText().isEmpty() 
                || txtAltRaz.getText().isEmpty() 
                || txtAltRFCC.getText().isEmpty() 
                || txtAltDom.getText().isEmpty() 
                || txtAltCorrC.getText().isEmpty()
                || txtModCont.getText().isEmpty()){
            btnModif.setEnabled(false);
        }else{
            btnModif.setEnabled(true);
        }
    }
    
    public void habilitarBotonE(){
        if(txtBajID.getText().isEmpty()){
            btnBuscarE.setEnabled(false);
        }else{
            btnBuscarE.setEnabled(true);
        }
    }
    
    public void habilitarBotonB(){
        if(txtConIDCan.getText().isEmpty()){
            btnBuscar.setEnabled(false);
        }else{
            btnBuscar.setEnabled(true);
        }
    }
    */
    /*public void validarCaracter(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()>=33 && evento.getKeyChar()<=64 
                || evento.getKeyChar()>=91 && evento.getKeyChar()<=96
                || evento.getKeyChar()>=123 && evento.getKeyChar()<=208
                || evento.getKeyChar()>=210 && evento.getKeyChar()<=240
                || evento.getKeyChar()>=242 && evento.getKeyChar()<=255){
            evento.consume();
            JOptionPane.showMessageDialog(this,"No se permiten caracteres especiales");
        }
    }
    private void insertarCliente(String emailCliente, String passwordCliente, String rsCliente, String rfcCLiente, String domicilioCliente, String cdfiCliente){
        /*INSERT
        1.- Crear una instancia del objeto DAOclientes
                DAOempleados nuevoEmpleado = new DAOempleados();
        2.- Creamos un nuevo objeto de tipo Empleados
                Empleados empleadoI = new Empleados();
                agregamos cada dato a empleadoI
                empleadoI.setRsCliente("");
                //o un constructor que inicialice todo
        3.- Una vez que se llenan los datos para el objeto empleadoI, ejecutar
                nuevoEmpleado.insert(empleadoI); //Devulve un entero si se aplico el INSERT, exactamente un 1 porque
                                        //esa es la cantidad de registros que inserto
        */
        
        /*DAOclientes nuevoCliente = new DAOclientes();
        Clientes cliente = new Clientes(emailCliente,passwordCliente,rsCliente,rfcCLiente,domicilioCliente,cdfiCliente);
        try {
            if(nuevoCliente.insert(cliente) != 0)
                JOptionPane.showMessageDialog(this,"Cliente dado de alta con exito");
            else
                JOptionPane.showMessageDialog(this,"El cliente no pudo ser dado de alta");
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarE;
    private javax.swing.JButton btnBuscarM;
    private javax.swing.JButton btnBuscarTds;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModif;
    private javax.swing.JComboBox<String> cmbCamEx;
    private javax.swing.JComboBox<String> cmbEx;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAltDur;
    private javax.swing.JLabel lblAltExp;
    private javax.swing.JLabel lblAltIDCli;
    private javax.swing.JLabel lblAltIDCli1;
    private javax.swing.JLabel lblAltOy;
    private javax.swing.JLabel lblAltRFC;
    private javax.swing.JLabel lblAvisoDisc;
    private javax.swing.JLabel lblAvisoDisc1;
    private javax.swing.JLabel lblAvisoExplicita;
    private javax.swing.JLabel lblAvisoExplicita1;
    private javax.swing.JLabel lblAvisoFE;
    private javax.swing.JLabel lblAvisoFE1;
    private javax.swing.JLabel lblAvisoID2;
    private javax.swing.JLabel lblAvisoID3;
    private javax.swing.JLabel lblAvisoIDAl;
    private javax.swing.JLabel lblAvisoIDC1;
    private javax.swing.JLabel lblAvisoIDC2;
    private javax.swing.JLabel lblAvisoIdArt;
    private javax.swing.JLabel lblAvisoIdArt1;
    private javax.swing.JLabel lblAvisoNombre;
    private javax.swing.JLabel lblAvisoNombre1;
    private javax.swing.JLabel lblAvisoRFC2;
    private javax.swing.JLabel lblBajID;
    private javax.swing.JLabel lblCamDis;
    private javax.swing.JLabel lblCamExp;
    private javax.swing.JLabel lblCamFE;
    private javax.swing.JLabel lblCamIdArt;
    private javax.swing.JLabel lblCamNom;
    private javax.swing.JLabel lblCamOy;
    private javax.swing.JLabel lblConsIdCan;
    private javax.swing.JLabel lblCorr1;
    private javax.swing.JLabel lblCorr2;
    private javax.swing.JLabel lblIdGen;
    private javax.swing.JPanel pnlAltas;
    private javax.swing.JPanel pnlAv;
    private javax.swing.JPanel pnlAv1;
    private javax.swing.JPanel pnlBajas;
    private javax.swing.JPanel pnlCambios;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JTabbedPane pnlPrincipal;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JTable tblClienteC;
    private javax.swing.JTable tblClienteE;
    private javax.swing.JTextField txtAltArt;
    private javax.swing.JTextField txtAltDisc;
    private javax.swing.JTextField txtAltDur2;
    private javax.swing.JTextField txtAltFE;
    private javax.swing.JTextField txtAltIDAl;
    private javax.swing.JTextField txtAltNom;
    private javax.swing.JTextField txtAltOy;
    private javax.swing.JTextField txtBajID;
    private javax.swing.JTextField txtCamDisc;
    private javax.swing.JTextField txtCamFE;
    private javax.swing.JTextField txtCamIDA;
    private javax.swing.JTextField txtCamIDG;
    private javax.swing.JTextField txtCamNom;
    private javax.swing.JTextField txtConIDCan;
    private javax.swing.JTextField txtModCont;
    private javax.swing.JTextField txtModCorr;
    // End of variables declaration//GEN-END:variables
    private int idEliminar = 0, idModificar = 0,empleadoModID = 0, idBuscar = 0;

    //private void agrgarElementosModif(Object[] clienteM) {
//        emailCliente,passwordCliente,rsCliente,rfcCLiente,domicilioCliente,cdfiCliente
       /* txtModCorr.setText(clienteM[1].toString());
        txtModCont.setText(clienteM[2].toString());
        txtModRaz.setText(clienteM[3].toString());
        txtModRFC.setText(clienteM[4].toString());
        txtModDom.setText(clienteM[5].toString());
//        txtModCont.setText(empleadoM[6].toString());        
    }*/
    
   /* private void habilitarCompMod(){
        txtModCorr.setEditable(true);
        txtModCont.setEditable(true);
        txtModRaz.setEditable(true);
        txtModRFC.setEditable(true);
        txtModDom.setEditable(true);
//        txtModCont.setEditable(true);
    }
    private void deshabilitarCompMod(){
        txtModCorr.setEditable(false);
        txtModCont.setEditable(false);
        txtModRaz.setEditable(false);
        txtModRFC.setEditable(false);
        txtModDom.setEditable(false);
//        txtModCont.setEditable(true);
    }*/
}
