package gui;

import dao.DAOartistas;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Artistas;

public class DlgArtistas extends javax.swing.JDialog {

    DefaultTableModel e, c;

    public DlgArtistas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setResizable(false);
        initComponents();
        e = (DefaultTableModel) tblClienteE.getModel();
        c = (DefaultTableModel) tblClienteC.getModel();
        //BOTON AGREGAR
        ImageIcon icagre = new ImageIcon(getClass().getResource("/Imagenes/agregar.png"));
        Icon iconoagre = new ImageIcon(icagre.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnAgregar.setIcon(iconoagre);
        //BOTON ELIMINAR
        ImageIcon icelim = new ImageIcon(getClass().getResource("/Imagenes/eliminar.png"));
        Icon iconoelim = new ImageIcon(icelim.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnBuscarE.setIcon(iconoelim);
        //BOTON BUSCAR
        ImageIcon icbuscar = new ImageIcon(getClass().getResource("/Imagenes/buscar.png"));
        Icon iconobuscar = new ImageIcon(icbuscar.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnBuscar.setIcon(iconobuscar);
        //BOTON MODIFICAR
        ImageIcon icmodif = new ImageIcon(getClass().getResource("/Imagenes/edit.png"));
        Icon iconomodif = new ImageIcon(icmodif.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnModif.setIcon(iconomodif);
        //Deshabilitar botones
        btnAgregar.setEnabled(false);
        btnBuscarE.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnModif.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JTabbedPane();
        pnlAltas = new javax.swing.JPanel();
        lblAltIDCli = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAltRFC = new javax.swing.JLabel();
        lblAltExp = new javax.swing.JLabel();
        lblAltDur = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        lblCorr1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtAltIDA = new javax.swing.JTextField();
        txtAltNom = new javax.swing.JTextField();
        txtAltDisc = new javax.swing.JTextField();
        txtAltSegu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAltRedesS = new javax.swing.JTextArea();
        pnlAv = new javax.swing.JPanel();
        lblAvisoIDA = new javax.swing.JLabel();
        lblAvisoNombre = new javax.swing.JLabel();
        lblAvisoSeg = new javax.swing.JLabel();
        lblAvisoRS = new javax.swing.JLabel();
        lblAvisoDisc = new javax.swing.JLabel();
        pnlBajas = new javax.swing.JPanel();
        lblBajID = new javax.swing.JLabel();
        txtBajID = new javax.swing.JTextField();
        btnBuscarE = new javax.swing.JButton();
        lblAvisoID2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClienteE = new javax.swing.JTable();
        btnEliminar1 = new javax.swing.JButton();
        pnlCambios = new javax.swing.JPanel();
        btnModif = new javax.swing.JButton();
        txtModCorr = new javax.swing.JTextField();
        lblCorr2 = new javax.swing.JLabel();
        txtModCont = new javax.swing.JTextField();
        btnBuscarM = new javax.swing.JButton();
        lblCamEL = new javax.swing.JLabel();
        lblCamDis = new javax.swing.JLabel();
        lblAltIDCli1 = new javax.swing.JLabel();
        lblCamNom = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtCamIDAr = new javax.swing.JTextField();
        txtCamNom = new javax.swing.JTextField();
        txtCamSeg = new javax.swing.JTextField();
        txtCamDisc = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtCamRedesS = new javax.swing.JTextArea();
        lblAvisoSegCam = new javax.swing.JLabel();
        lblAvisoDiscCam = new javax.swing.JLabel();
        lblAvisoNomCam = new javax.swing.JLabel();
        lblAvisoIDartCam = new javax.swing.JLabel();
        lblAvisoRsCam = new javax.swing.JLabel();
        lblCamExp = new javax.swing.JLabel();
        pnlAv1 = new javax.swing.JPanel();
        lblAvisoIDAr1 = new javax.swing.JLabel();
        lblAvisoNombre1 = new javax.swing.JLabel();
        lblAvisoSeguidores1 = new javax.swing.JLabel();
        lblAvisoRS1 = new javax.swing.JLabel();
        lblAvisoDisc1 = new javax.swing.JLabel();
        pnlConsultas = new javax.swing.JPanel();
        lblConsIdCan = new javax.swing.JLabel();
        txtConIDArt = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblAvisoID3 = new javax.swing.JLabel();
        btnBuscarTds = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClienteC = new javax.swing.JTable();
        pnlReportes = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ARTISTAS");

        pnlPrincipal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblAltIDCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltIDCli.setText("ID Artista:");

        lblAltRFC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltRFC.setText("Nombre");

        lblAltExp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltExp.setText("Seguidores");

        lblAltDur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltDur.setText("Redes Sociales");

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblCorr1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCorr1.setText("Discografia");

        txtAltIDA.setEditable(false);
        txtAltIDA.setText("0");
        txtAltIDA.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltIDA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltIDAKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltIDAKeyTyped(evt);
            }
        });

        txtAltNom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltNomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltNomKeyTyped(evt);
            }
        });

        txtAltDisc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltDiscActionPerformed(evt);
            }
        });
        txtAltDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltDiscKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltDiscKeyTyped(evt);
            }
        });

        txtAltSegu.setEditable(false);
        txtAltSegu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltSegu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltSeguActionPerformed(evt);
            }
        });
        txtAltSegu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltSeguKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltSeguKeyTyped(evt);
            }
        });

        txtAltRedesS.setColumns(20);
        txtAltRedesS.setRows(5);
        txtAltRedesS.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        jScrollPane1.setViewportView(txtAltRedesS);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtAltSegu, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                        .addComponent(txtAltIDA, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtAltNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAltDisc, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtAltIDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtAltNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltSegu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(txtAltDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        lblAvisoIDA.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDA.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoNombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoNombre.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoSeg.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoSeg.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoRS.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoRS.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoDisc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoDisc.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlAvLayout = new javax.swing.GroupLayout(pnlAv);
        pnlAv.setLayout(pnlAvLayout);
        pnlAvLayout.setHorizontalGroup(
            pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvisoIDA, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAvLayout.createSequentialGroup()
                        .addComponent(lblAvisoDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAvisoSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAvisoRS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAvLayout.setVerticalGroup(
            pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvLayout.createSequentialGroup()
                .addComponent(lblAvisoIDA, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAvisoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAvisoSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblAvisoRS, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAltasLayout = new javax.swing.GroupLayout(pnlAltas);
        pnlAltas.setLayout(pnlAltasLayout);
        pnlAltasLayout.setHorizontalGroup(
            pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAltRFC)
                    .addComponent(lblAltExp)
                    .addComponent(lblAltDur)
                    .addGroup(pnlAltasLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2))
                    .addComponent(lblAltIDCli)
                    .addComponent(lblCorr1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAv, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        pnlAltasLayout.setVerticalGroup(
            pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAltasLayout.createSequentialGroup()
                        .addComponent(lblAltIDCli)
                        .addGap(18, 18, 18)
                        .addComponent(lblAltRFC)
                        .addGap(18, 18, 18)
                        .addComponent(lblAltExp)
                        .addGap(26, 26, 26)
                        .addComponent(lblCorr1)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblAltDur))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(51, 51, 51)
                .addComponent(btnAgregar)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("ALTAS", pnlAltas);

        lblBajID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBajID.setText("ID Artista:");

        txtBajID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtBajID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBajIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBajIDKeyTyped(evt);
            }
        });

        btnBuscarE.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarE.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarE.setText("BUSCAR");
        btnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEActionPerformed(evt);
            }
        });

        lblAvisoID2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoID2.setForeground(new java.awt.Color(255, 0, 0));

        tblClienteE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Email", "Contraseña", "Razon Social", "RFC", "Domicilio", "CDFI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblClienteE);

        btnEliminar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.setEnabled(false);
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBajasLayout = new javax.swing.GroupLayout(pnlBajas);
        pnlBajas.setLayout(pnlBajasLayout);
        pnlBajasLayout.setHorizontalGroup(
            pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBajasLayout.createSequentialGroup()
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblBajID)
                        .addGap(46, 46, 46)
                        .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarE)
                            .addGroup(pnlBajasLayout.createSequentialGroup()
                                .addComponent(txtBajID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblAvisoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBajasLayout.createSequentialGroup()
                    .addGap(323, 323, 323)
                    .addComponent(btnEliminar1)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );
        pnlBajasLayout.setVerticalGroup(
            pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBajasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBajID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBajID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarE))
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblAvisoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBajasLayout.createSequentialGroup()
                    .addContainerGap(371, Short.MAX_VALUE)
                    .addComponent(btnEliminar1)
                    .addGap(56, 56, 56)))
        );

        pnlPrincipal.addTab("BAJAS", pnlBajas);

        btnModif.setBackground(new java.awt.Color(255, 255, 255));
        btnModif.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnModif.setText("MODIFICAR");
        btnModif.setEnabled(false);
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });

        txtModCorr.setEditable(false);
        txtModCorr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtModCorr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModCorrKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModCorrKeyTyped(evt);
            }
        });

        lblCorr2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCorr2.setText("Contraseña:");

        txtModCont.setEditable(false);
        txtModCont.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtModCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModContActionPerformed(evt);
            }
        });
        txtModCont.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtModContKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtModContKeyTyped(evt);
            }
        });

        btnBuscarM.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarM.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarM.setText("BUSCAR");
        btnBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMActionPerformed(evt);
            }
        });

        lblCamEL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamEL.setText("Redes Sociales");

        lblCamDis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamDis.setText("Discografia");

        lblAltIDCli1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltIDCli1.setText("ID Artista:");

        lblCamNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamNom.setText("Nombre");

        txtCamIDAr.setEditable(false);
        txtCamIDAr.setText("0");
        txtCamIDAr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamIDAr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamIDArKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamIDArKeyTyped(evt);
            }
        });

        txtCamNom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamNomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamNomKeyTyped(evt);
            }
        });

        txtCamSeg.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamSeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamSegKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamSegKeyTyped(evt);
            }
        });

        txtCamDisc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamDiscActionPerformed(evt);
            }
        });
        txtCamDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamDiscKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamDiscKeyTyped(evt);
            }
        });

        txtCamRedesS.setColumns(20);
        txtCamRedesS.setRows(5);
        txtCamRedesS.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        jScrollPane2.setViewportView(txtCamRedesS);

        lblAvisoSegCam.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoSegCam.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoDiscCam.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoDiscCam.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoNomCam.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoNomCam.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoIDartCam.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDartCam.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoRsCam.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoRsCam.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblAvisoRsCam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCamNom)
                            .addComponent(txtCamIDAr)
                            .addComponent(txtCamSeg, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(txtCamDisc))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAvisoDiscCam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvisoNomCam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvisoSegCam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvisoIDartCam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCamIDAr, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoIDartCam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCamNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoNomCam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCamSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoSegCam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtCamDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAvisoRsCam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblAvisoDiscCam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblCamExp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamExp.setText("Seguidores");

        lblAvisoIDAr1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDAr1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoNombre1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoNombre1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoSeguidores1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoSeguidores1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoRS1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoRS1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoDisc1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoDisc1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlAv1Layout = new javax.swing.GroupLayout(pnlAv1);
        pnlAv1.setLayout(pnlAv1Layout);
        pnlAv1Layout.setHorizontalGroup(
            pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAv1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvisoIDAr1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoSeguidores1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoRS1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoDisc1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAv1Layout.setVerticalGroup(
            pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAv1Layout.createSequentialGroup()
                .addComponent(lblAvisoIDAr1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAvisoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAvisoSeguidores1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvisoDisc1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAvisoRS1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlCambiosLayout = new javax.swing.GroupLayout(pnlCambios);
        pnlCambios.setLayout(pnlCambiosLayout);
        pnlCambiosLayout.setHorizontalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnModif))
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblCamExp)
                                .addGap(51, 51, 51))
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCamEL)
                                    .addComponent(lblCamDis)
                                    .addComponent(lblCamNom)
                                    .addComponent(lblAltIDCli1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(btnBuscarM)
                        .addGap(18, 18, 18)
                        .addComponent(pnlAv1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCorr2)
                .addGap(48, 48, 48)
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtModCorr, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtModCont, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
        );
        pnlCambiosLayout.setVerticalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblAltIDCli1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCamNom)
                                .addGap(18, 18, 18)
                                .addComponent(lblCamExp)
                                .addGap(18, 18, 18)
                                .addComponent(lblCamDis)
                                .addGap(18, 18, 18)
                                .addComponent(lblCamEL))
                            .addComponent(pnlAv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnModif))
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtModCorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarM))
                        .addGap(85, 85, 85)
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCorr2)
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(txtModCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("CAMBIOS", pnlCambios);

        lblConsIdCan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConsIdCan.setText("ID Artista:");

        txtConIDArt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtConIDArt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConIDArtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConIDArtKeyTyped(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblAvisoID3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoID3.setForeground(new java.awt.Color(255, 0, 0));

        btnBuscarTds.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarTds.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarTds.setText("MOSTRAR TODOS");
        btnBuscarTds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTdsActionPerformed(evt);
            }
        });

        tblClienteC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_artista", "nombre_artista", "seguidores_artista", "discografia", "RFC"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblClienteC);

        javax.swing.GroupLayout pnlConsultasLayout = new javax.swing.GroupLayout(pnlConsultas);
        pnlConsultas.setLayout(pnlConsultasLayout);
        pnlConsultasLayout.setHorizontalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblConsIdCan)
                        .addGap(45, 45, 45)
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConIDArt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlConsultasLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnBuscar)))
                        .addGap(73, 73, 73)
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarTds)
                            .addComponent(lblAvisoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConsultasLayout.setVerticalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConsIdCan)
                        .addComponent(txtConIDArt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAvisoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(btnBuscarTds))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("CONSULTAS", pnlConsultas);

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
        );

        pnlPrincipal.addTab("REPORTES", pnlReportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTdsActionPerformed
        Object artistaC[] = new Object[4];
        DAOartistas artista = new DAOartistas();
        ArrayList<Artistas> artistas = null;
        while (c.getRowCount() > 0) {
            c.removeRow(0);
        }
        if (c.getRowCount() == 0) {
            try {
                artistas = artista.select();
                for (Artistas art : artistas) {

                    artistaC[0] = art.getId_artista();
                    artistaC[1] = art.getNombre_artista();
                    artistaC[2] = art.getSeguidores_artista();
                    artistaC[3] = art.getDiscografia();
                    artistaC[4] = art.getRedes_sociales();

                    c.addRow(artistaC);
                }
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
        }
        txtConIDArt.setText("");
    }//GEN-LAST:event_btnBuscarTdsActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        boolean encontrado = false;
        idBuscar = Integer.parseInt(txtConIDArt.getText());
        Object artistaM[] = new Object[4];
        DAOartistas artista = new DAOartistas();
        ArrayList<Artistas> artistas = null;

        try {
            artistas = artista.select();
            for (Artistas art : artistas) {
                if (art.getId_artista() == idBuscar) {

                    artistaM[0] = art.getId_artista();
                    artistaM[1] = art.getNombre_artista();
                    artistaM[2] = art.getSeguidores_artista();
                    artistaM[3] = art.getDiscografia();
                    artistaM[4] = art.getRedes_sociales();

                    encontrado = true;
                    break;
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        if (encontrado) {
            while (c.getRowCount() > 0) {
                c.removeRow(0);
            }
            if (c.getRowCount() == 0) {
                c.addRow(artistaM);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Artista no encontrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtConIDArtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConIDArtKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtConIDArtKeyTyped

    private void txtConIDArtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConIDArtKeyReleased
        habilitarBotonB();
        validarVacios3();
    }//GEN-LAST:event_txtConIDArtKeyReleased

    private void btnBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMActionPerformed
        boolean artistaEncontrado = false;
        idModificar = Integer.parseInt(txtCamIDAr.getText());
        Object artistaM[] = new Object[4];
        DAOartistas artista = new DAOartistas();
        ArrayList<Artistas> artistas = null;

        try {
            artistas = artista.select();
            for (Artistas art : artistas) {
                if (art.getId_artista() == idModificar) {
                    artistaM[0] = art.getId_artista();
                    artistaM[1] = art.getNombre_artista();
                    artistaM[2] = art.getSeguidores_artista();
                    artistaM[3] = art.getDiscografia();
                    artistaM[4] = art.getRedes_sociales();
                    artistaEncontrado = true;
                    break;
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        if (artistaEncontrado) {
            btnModif.setEnabled(true);
            //habilitarCompMod();
            //agrgarElementosModif(clienteM);
        } else
            JOptionPane.showMessageDialog(this, "Artista no encontrado");
    }//GEN-LAST:event_btnBuscarMActionPerformed

    private void txtModContKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModContKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModContKeyTyped

    private void txtModContKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModContKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModContKeyReleased

    private void txtModContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModContActionPerformed

    private void txtModCorrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModCorrKeyTyped
        //validarCorreo(evt);
    }//GEN-LAST:event_txtModCorrKeyTyped

    private void txtModCorrKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModCorrKeyReleased
        //habilitarBotonM();
        //validarVacios1();
    }//GEN-LAST:event_txtModCorrKeyReleased

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        artistaModID = Integer.parseInt(txtCamIDAr.getText());
        String artistaCamNombre = txtCamNom.getText();
        int artistaCamSeg = Integer.parseInt(txtCamSeg.getText());
        String artistaCamDisc = txtCamDisc.getText();
        String artistaCamRS = txtCamRedesS.getText();

        DAOartistas artista = new DAOartistas();
        Artistas artistaU = new Artistas();
        artistaU.setId_artista(artistaModID);
        artistaU.setNombre_artista(artistaCamNombre);
        artistaU.setSeguidores_artista(artistaCamSeg);
        artistaU.setDiscografia(artistaCamDisc);
        artistaU.setRedes_sociales(artistaCamRS);

        try {
            if (artista.update(artistaU) != 0) {
                JOptionPane.showMessageDialog(this, "Empleado modificado con exito");
                deshabilitarCompMod();
            } else {
                JOptionPane.showMessageDialog(this, "El empleado no se modifico");
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnModifActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed

        if (idEliminar != 0) {
            DAOartistas artista = new DAOartistas();
            Artistas deleteArtista = new Artistas();
            deleteArtista.setId_artista(idEliminar);
            try {
                if (artista.delete(deleteArtista) != 0) {
                    JOptionPane.showMessageDialog(this, "Artista eliminado con exito");
                    txtBajID.setText("");
                    txtBajID.removeAll();
                } else {
                    JOptionPane.showMessageDialog(this, "Hubo un error al eliminar al artista");
                }
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
        }
        while (e.getRowCount() > 0) {
            e.removeRow(0);
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEActionPerformed
        boolean artistaEncontrado = false;
        idEliminar = Integer.parseInt(txtBajID.getText());
        Object clienteE[] = new Object[5];
        DAOartistas artista = new DAOartistas();
        ArrayList<Artistas> artistass = null;

        try {
            artistass = artista.select();
            for (Artistas art : artistass) {
                if (art.getId_artista() == idEliminar) {
                    clienteE[0] = art.getId_artista();
                    clienteE[1] = art.getNombre_artista();
                    clienteE[2] = art.getSeguidores_artista();
                    clienteE[3] = art.getDiscografia();
                    clienteE[4] = art.getRedes_sociales();

                    artistaEncontrado = true;
                    break;
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        while (e.getRowCount() > 0) {
            e.removeRow(0);
        }
        if (artistaEncontrado) {

            if (e.getRowCount() == 0) {
                e.addRow(clienteE);
                btnEliminar1.setEnabled(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Artista no encontrado");
        }
    }//GEN-LAST:event_btnBuscarEActionPerformed

    private void txtBajIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBajIDKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtBajIDKeyTyped

    private void txtBajIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBajIDKeyReleased
        habilitarBotonE();
        validarVacios2();
    }//GEN-LAST:event_txtBajIDKeyReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int idArtista = Integer.parseInt(txtAltIDA.getText());
        String nombreArtista = txtAltNom.getText();
        int seguidoresArtista = Integer.parseInt(txtAltSegu.getText());
        String discografiaArtista = txtAltDisc.getText();
        String redesArtista = txtAltRedesS.getText();

        //        emailCliente,passwordCliente,rsCliente,rfcCLiente,domicilioCliente,cdfiCliente
        insertarArtista(idArtista, nombreArtista, seguidoresArtista, discografiaArtista, redesArtista);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtAltDiscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltDiscKeyTyped
        validarCaracter(evt);
    }//GEN-LAST:event_txtAltDiscKeyTyped

    private void txtAltDiscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltDiscKeyReleased
        habilitarBoton();
        validarVacios();
    }//GEN-LAST:event_txtAltDiscKeyReleased

    private void txtAltDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltDiscActionPerformed

    private void txtAltNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltNomKeyTyped
        validarCaracter(evt);
    }//GEN-LAST:event_txtAltNomKeyTyped

    private void txtAltNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltNomKeyReleased
        habilitarBoton();
        validarVacios();
    }//GEN-LAST:event_txtAltNomKeyReleased

    private void txtAltIDAKeyReleased(java.awt.event.KeyEvent evt) {
        validarNumeros(evt);
    }
    private void txtAltIDAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltIDAKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtAltIDAKeyTyped

//GEN-FIRST:event_txtAltIDCKeyReleased
 
//GEN-LAST:event_txtAltIDCKeyReleased

    private void txtAltSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltSegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltSegActionPerformed

    private void txtAltSegKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltSegKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltSegKeyReleased

    private void txtAltSegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltSegKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltSegKeyTyped

    private void txtCamIDArKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDArKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamIDArKeyReleased

    private void txtCamIDArKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDArKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamIDArKeyTyped

    private void txtCamNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamNomKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamNomKeyReleased

    private void txtCamNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamNomKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamNomKeyTyped

    private void txtCamSegKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamSegKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamSegKeyReleased

    private void txtCamSegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamSegKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamSegKeyTyped

    private void txtCamDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamDiscActionPerformed

    private void txtCamDiscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamDiscKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamDiscKeyReleased

    private void txtCamDiscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamDiscKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamDiscKeyTyped
    private void txtAltSeguKeyReleased(java.awt.event.KeyEvent evt) {

    }

    private void txtAltSeguActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void txtAltSeguKeyTyped(java.awt.event.KeyEvent evt) {

    }

    public void validarVacios() {
        if (txtAltIDA.getText().isEmpty()) { //id_artista
            lblAvisoIDA.setText("Campo obligatorio");
        } else {
            lblAvisoIDA.setText("");
        }
        if (txtAltNom.getText().isEmpty()) { //nombre_artista
            lblAvisoNombre.setText("Campo obligatorio");
        } else {
            lblAvisoNombre.setText("");
        }
        if (txtAltSegu.getText().isEmpty()) { //seguidores_artista
            lblAvisoSeg.setText("Campo obligatorio");
        } else {
            lblAvisoSeg.setText("");
        }
        if (txtAltDisc.getText().isEmpty()) { //discografia
            lblAvisoDisc.setText("Campo obligatorio");
        } else {
            lblAvisoDisc.setText("");
        }
        if (txtAltDisc.getText().isEmpty()) {
            lblAvisoDisc.setText("Campo obligatorio");
        } else {
            lblAvisoDisc.setText("");
        }
        if (txtAltRedesS.getText().isEmpty()) {
            lblAvisoRS.setText("Campo obligatorio");
        } else {
            lblAvisoRS.setText("");
        }
    }

    public void validarVacios1() {
        if (txtCamIDAr.getText().isEmpty()) {
            lblAvisoIDartCam.setText("Campo obligatorio");
        } else {
            lblAvisoIDartCam.setText("");
        }
        if (txtCamNom.getText().isEmpty()) {
            lblAvisoNomCam.setText("Campo obligatorio");
        } else {
            lblAvisoNomCam.setText("");
        }
        if (txtCamSeg.getText().isEmpty()) {
            lblAvisoSegCam.setText("Campo obligatorio");
        } else {
            lblAvisoSegCam.setText("");
        }
        if (txtCamDisc.getText().isEmpty()) {
            lblAvisoDiscCam.setText("Campo obligatorio");
        } else {
            lblAvisoDiscCam.setText("");
        }
        if (txtCamRedesS.getText().isEmpty()) {
            lblAvisoRsCam.setText("Campo obligatorio");
        } else {
            lblAvisoRsCam.setText("");
        }
    }

    public void validarVacios2() {
        if (txtBajID.getText().isEmpty()) {
            lblAvisoID2.setText("ID obligatorio");
        } else {
            lblAvisoID2.setText("");
        }
    }

    public void validarVacios3() {
        if (txtConIDArt.getText().isEmpty()) {
            lblAvisoID3.setText("ID obligatorio");
        } else {
            lblAvisoID3.setText("");
        }
    }

    public void validarNumeros(java.awt.event.KeyEvent evento) {
        if (evento.getKeyChar() >= 32 && evento.getKeyChar() <= 47
                || evento.getKeyChar() >= 58 && evento.getKeyChar() <= 255) {
            evento.consume();
            JOptionPane.showMessageDialog(this, "Solo Numeros");
        }
    }

    public void habilitarBoton() {
        if (txtAltIDA.getText().isEmpty()
                || txtAltNom.getText().isEmpty()
                || txtAltSegu.getText().isEmpty()
                || txtAltDisc.getText().isEmpty()
                || txtAltRedesS.getText().isEmpty()) {
            btnAgregar.setEnabled(false);
        } else {
            btnAgregar.setEnabled(true);
        }
    }

    public void habilitarBotonM() {
        if (txtAltIDA.getText().isEmpty()
                || txtAltNom.getText().isEmpty()
                || txtAltSegu.getText().isEmpty()
                || txtAltDisc.getText().isEmpty()
                || txtAltRedesS.getText().isEmpty()) {
            btnModif.setEnabled(false);
        } else {
            btnModif.setEnabled(true);
        }
    }

    public void habilitarBotonE() {
        if (txtBajID.getText().isEmpty()) {
            btnBuscarE.setEnabled(false);
        } else {
            btnBuscarE.setEnabled(true);
        }
    }

    public void habilitarBotonB() {
        if (txtConIDArt.getText().isEmpty()) {
            btnBuscar.setEnabled(false);
        } else {
            btnBuscar.setEnabled(true);
        }
    }

    public void validarCaracter(java.awt.event.KeyEvent evento) {
        if (evento.getKeyChar() >= 33 && evento.getKeyChar() <= 64
                || evento.getKeyChar() >= 91 && evento.getKeyChar() <= 96
                || evento.getKeyChar() >= 123 && evento.getKeyChar() <= 208
                || evento.getKeyChar() >= 210 && evento.getKeyChar() <= 240
                || evento.getKeyChar() >= 242 && evento.getKeyChar() <= 255) {
            evento.consume();
            JOptionPane.showMessageDialog(this, "No se permiten caracteres especiales");
        }
    }

    private void insertarArtista(int id_artista, String nombre_artista, int seguidores_artista, String discografia, String redes_sociales) {

        DAOartistas nuevoArtista = new DAOartistas();
        Artistas artista = new Artistas(id_artista, nombre_artista, seguidores_artista, discografia, redes_sociales);
        try {
            if (nuevoArtista.insert(artista) != 0) {
                JOptionPane.showMessageDialog(this, "Artista dado de alta con exito");
            } else {
                JOptionPane.showMessageDialog(this, "El artista no pudo ser dado de alta");
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarE;
    private javax.swing.JButton btnBuscarM;
    private javax.swing.JButton btnBuscarTds;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModif;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAltDur;
    private javax.swing.JLabel lblAltExp;
    private javax.swing.JLabel lblAltIDCli;
    private javax.swing.JLabel lblAltIDCli1;
    private javax.swing.JLabel lblAltRFC;
    private javax.swing.JLabel lblAvisoDisc;
    private javax.swing.JLabel lblAvisoDisc1;
    private javax.swing.JLabel lblAvisoDiscCam;
    private javax.swing.JLabel lblAvisoID2;
    private javax.swing.JLabel lblAvisoID3;
    private javax.swing.JLabel lblAvisoIDA;
    private javax.swing.JLabel lblAvisoIDAr1;
    private javax.swing.JLabel lblAvisoIDartCam;
    private javax.swing.JLabel lblAvisoNomCam;
    private javax.swing.JLabel lblAvisoNombre;
    private javax.swing.JLabel lblAvisoNombre1;
    private javax.swing.JLabel lblAvisoRS;
    private javax.swing.JLabel lblAvisoRS1;
    private javax.swing.JLabel lblAvisoRsCam;
    private javax.swing.JLabel lblAvisoSeg;
    private javax.swing.JLabel lblAvisoSegCam;
    private javax.swing.JLabel lblAvisoSeguidores1;
    private javax.swing.JLabel lblBajID;
    private javax.swing.JLabel lblCamDis;
    private javax.swing.JLabel lblCamEL;
    private javax.swing.JLabel lblCamExp;
    private javax.swing.JLabel lblCamNom;
    private javax.swing.JLabel lblConsIdCan;
    private javax.swing.JLabel lblCorr1;
    private javax.swing.JLabel lblCorr2;
    private javax.swing.JPanel pnlAltas;
    private javax.swing.JPanel pnlAv;
    private javax.swing.JPanel pnlAv1;
    private javax.swing.JPanel pnlBajas;
    private javax.swing.JPanel pnlCambios;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JTabbedPane pnlPrincipal;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JTable tblClienteC;
    private javax.swing.JTable tblClienteE;
    private javax.swing.JTextField txtAltDisc;
    private javax.swing.JTextField txtAltIDA;
    private javax.swing.JTextField txtAltNom;
    private javax.swing.JTextArea txtAltRedesS;
    private javax.swing.JTextField txtAltSegu;
    private javax.swing.JTextField txtBajID;
    private javax.swing.JTextField txtCamDisc;
    private javax.swing.JTextField txtCamIDAr;
    private javax.swing.JTextField txtCamNom;
    private javax.swing.JTextArea txtCamRedesS;
    private javax.swing.JTextField txtCamSeg;
    private javax.swing.JTextField txtConIDArt;
    private javax.swing.JTextField txtModCont;
    private javax.swing.JTextField txtModCorr;
    // End of variables declaration//GEN-END:variables
    private int idEliminar = 0, idModificar = 0, artistaModID = 0, idBuscar = 0;

    private void agrgarElementosModif(Object[] clienteM) {
//        emailCliente,passwordCliente,rsCliente,rfcCLiente,domicilioCliente,cdfiCliente
        txtCamIDAr.setText(clienteM[1].toString());
        txtCamNom.setText(clienteM[1].toString());
        txtCamSeg.setText(clienteM[2].toString());
        txtCamDisc.setText(clienteM[3].toString());
        txtCamRedesS.setText(clienteM[4].toString());

    }

    private void habilitarCompMod() {
        txtCamIDAr.setEditable(true);
        txtCamNom.setEditable(true);
        txtCamSeg.setEditable(true);
        txtCamDisc.setEditable(true);
        txtCamRedesS.setEditable(true);
    }

    private void deshabilitarCompMod() {
        txtCamIDAr.setEditable(false);
        txtCamNom.setEditable(false);
        txtCamSeg.setEditable(false);
        txtCamDisc.setEditable(false);
        txtCamRedesS.setEditable(false);
    }
}
