package gui;

import dao.DAOcanciones;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Canciones;

public class DlgCanciones extends javax.swing.JDialog {
    DefaultTableModel e,c;
    public DlgCanciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setResizable(false);
        initComponents();
        e = (DefaultTableModel)tblClienteE.getModel();
        c = (DefaultTableModel)tblClienteC.getModel();
        //BOTON AGREGAR
        ImageIcon icagre=new ImageIcon(getClass().getResource("/Imagenes/agregar.png"));
        Icon iconoagre=new ImageIcon(icagre.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnAgregar.setIcon(iconoagre);
        //BOTON ELIMINAR
        ImageIcon icelim=new ImageIcon(getClass().getResource("/Imagenes/eliminar.png"));
        Icon iconoelim=new ImageIcon(icelim.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnBuscarE.setIcon(iconoelim);
        //BOTON BUSCAR
        ImageIcon icbuscar=new ImageIcon(getClass().getResource("/Imagenes/buscar.png"));
        Icon iconobuscar=new ImageIcon(icbuscar.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnBuscar.setIcon(iconobuscar);
        //BOTON MODIFICAR
        ImageIcon icmodif=new ImageIcon(getClass().getResource("/Imagenes/edit.png"));
        Icon iconomodif=new ImageIcon(icmodif.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnModif.setIcon(iconomodif);
        //Deshabilitar botones
        btnAgregar.setEnabled(false);
        btnBuscarE.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnModif.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JTabbedPane();
        pnlAltas = new javax.swing.JPanel();
        lblAltIDCli = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIdGen = new javax.swing.JLabel();
        lblAltRFC = new javax.swing.JLabel();
        lblAltExp = new javax.swing.JLabel();
        lblAltDur = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        lblCorr1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtAltIDC = new javax.swing.JTextField();
        txtAltIdGen = new javax.swing.JTextField();
        txtAltNombre = new javax.swing.JTextField();
        cmbAltExp = new javax.swing.JComboBox<>();
        txtAltDisc = new javax.swing.JTextField();
        txtAltDur = new javax.swing.JTextField();
        txtAltOy = new javax.swing.JTextField();
        cmbAltEL = new javax.swing.JComboBox<>();
        pnlAv = new javax.swing.JPanel();
        lblAvisoIDC = new javax.swing.JLabel();
        lblAvisoIdGen = new javax.swing.JLabel();
        lblAvisoNombre = new javax.swing.JLabel();
        lblAvisoExplicita = new javax.swing.JLabel();
        lblAvisoDur = new javax.swing.JLabel();
        lblAvisoEL = new javax.swing.JLabel();
        lblAvisoDisc = new javax.swing.JLabel();
        lblAltOy = new javax.swing.JLabel();
        lblAltOy1 = new javax.swing.JLabel();
        pnlBajas = new javax.swing.JPanel();
        lblBajID = new javax.swing.JLabel();
        txtBajID = new javax.swing.JTextField();
        btnBuscarE = new javax.swing.JButton();
        lblAvisoID2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClienteE = new javax.swing.JTable();
        btnEliminar1 = new javax.swing.JButton();
        pnlCambios = new javax.swing.JPanel();
        btnModif = new javax.swing.JButton();
        btnBuscarM = new javax.swing.JButton();
        lblCamDur = new javax.swing.JLabel();
        lblCamEL = new javax.swing.JLabel();
        lblCamDis = new javax.swing.JLabel();
        lblAltIDCli1 = new javax.swing.JLabel();
        lblIdGen1 = new javax.swing.JLabel();
        lblCamNom = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtCamIDC = new javax.swing.JTextField();
        txtCamNom = new javax.swing.JTextField();
        txtCamDur = new javax.swing.JTextField();
        cmbCamEx = new javax.swing.JComboBox<>();
        txtCamDisc = new javax.swing.JTextField();
        txtCamOy = new javax.swing.JTextField();
        cmbCamEL = new javax.swing.JComboBox<>();
        txtCamIDG = new javax.swing.JTextField();
        lblCamExp = new javax.swing.JLabel();
        lblCamOy = new javax.swing.JLabel();
        pnlAv1 = new javax.swing.JPanel();
        lblAvisoIDC1 = new javax.swing.JLabel();
        lblAvisoIdGen1 = new javax.swing.JLabel();
        lblAvisoNombre1 = new javax.swing.JLabel();
        lblAvisoExplicita1 = new javax.swing.JLabel();
        lblAvisoDur1 = new javax.swing.JLabel();
        lblAvisoEL1 = new javax.swing.JLabel();
        lblAvisoDisc1 = new javax.swing.JLabel();
        pnlConsultas = new javax.swing.JPanel();
        lblConsIdCan = new javax.swing.JLabel();
        txtConIDCan = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblAvisoID3 = new javax.swing.JLabel();
        btnBuscarTds = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClienteC = new javax.swing.JTable();
        pnlReportes = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CANCIONES");

        pnlPrincipal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblAltIDCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltIDCli.setText("ID Cancion:");

        lblIdGen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdGen.setText("ID Genero:");

        lblAltRFC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltRFC.setText("Nombre");

        lblAltExp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltExp.setText("Explicita");

        lblAltDur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltDur.setText("Duracion");

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lblCorr1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCorr1.setText("Discografia");

        txtAltIDC.setText("0");
        txtAltIDC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltIDC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltIDCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltIDCKeyTyped(evt);
            }
        });

        txtAltIdGen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltIdGen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltIdGenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltIdGenKeyTyped(evt);
            }
        });

        txtAltNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltNombreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltNombreKeyTyped(evt);
            }
        });

        cmbAltExp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbAltExp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "SI", "NO" }));

        txtAltDisc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltDiscActionPerformed(evt);
            }
        });
        txtAltDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltDiscKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltDiscKeyTyped(evt);
            }
        });

        txtAltDur.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltDur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltDurActionPerformed(evt);
            }
        });
        txtAltDur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltDurKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltDurKeyTyped(evt);
            }
        });

        txtAltOy.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltOy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltOyActionPerformed(evt);
            }
        });
        txtAltOy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltOyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltOyKeyTyped(evt);
            }
        });

        cmbAltEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbAltEL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "FREEUSE", "COPYRIGHT" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbAltEL, 0, 131, Short.MAX_VALUE)
                    .addComponent(txtAltOy, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtAltIDC, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAltIdGen, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbAltExp, javax.swing.GroupLayout.Alignment.LEADING, 0, 131, Short.MAX_VALUE)
                    .addComponent(txtAltNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAltDisc, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAltDur, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtAltIDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltIdGen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbAltExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltDur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltOy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbAltEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        lblAvisoIDC.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDC.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoIdGen.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIdGen.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoNombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoNombre.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoExplicita.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoExplicita.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoDur.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoDur.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoEL.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoEL.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoDisc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoDisc.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlAvLayout = new javax.swing.GroupLayout(pnlAv);
        pnlAv.setLayout(pnlAvLayout);
        pnlAvLayout.setHorizontalGroup(
            pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvisoIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoExplicita, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoDur, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoEL, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAvLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblAvisoIdGen, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        pnlAvLayout.setVerticalGroup(
            pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvLayout.createSequentialGroup()
                .addComponent(lblAvisoIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblAvisoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvisoExplicita, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAvisoDur, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(lblAvisoEL, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAvisoDisc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAvLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(lblAvisoIdGen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(230, Short.MAX_VALUE)))
        );

        lblAltOy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltOy.setText("Oyentes");

        lblAltOy1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltOy1.setText("Estatus Legal");

        javax.swing.GroupLayout pnlAltasLayout = new javax.swing.GroupLayout(pnlAltas);
        pnlAltas.setLayout(pnlAltasLayout);
        pnlAltasLayout.setHorizontalGroup(
            pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAltasLayout.createSequentialGroup()
                        .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAltRFC)
                            .addComponent(lblAltExp)
                            .addComponent(lblAltDur)
                            .addComponent(lblAltOy)
                            .addComponent(lblCorr1)
                            .addGroup(pnlAltasLayout.createSequentialGroup()
                                .addComponent(lblIdGen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(lblAltIDCli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAltasLayout.createSequentialGroup()
                        .addComponent(lblAltOy1)
                        .addGap(18, 18, 18)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pnlAv, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAltasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(199, 199, 199))
        );
        pnlAltasLayout.setVerticalGroup(
            pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlAltasLayout.createSequentialGroup()
                        .addComponent(lblAltIDCli)
                        .addGap(9, 9, 9)
                        .addComponent(lblIdGen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(lblAltRFC)
                        .addGap(18, 18, 18)
                        .addComponent(lblAltExp)
                        .addGap(26, 26, 26)
                        .addComponent(lblAltDur)
                        .addGap(18, 18, 18)
                        .addComponent(lblAltOy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAltOy1)
                        .addGap(18, 18, 18)
                        .addComponent(lblCorr1)
                        .addGap(21, 21, 21))
                    .addComponent(pnlAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("ALTAS", pnlAltas);

        lblBajID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBajID.setText("ID Cancion:");

        txtBajID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtBajID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBajIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBajIDKeyTyped(evt);
            }
        });

        btnBuscarE.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarE.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarE.setText("BUSCAR");
        btnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEActionPerformed(evt);
            }
        });

        lblAvisoID2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoID2.setForeground(new java.awt.Color(255, 0, 0));

        tblClienteE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Email", "Contraseña", "Razon Social", "RFC", "Domicilio", "CDFI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblClienteE);

        btnEliminar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.setEnabled(false);
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBajasLayout = new javax.swing.GroupLayout(pnlBajas);
        pnlBajas.setLayout(pnlBajasLayout);
        pnlBajasLayout.setHorizontalGroup(
            pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBajasLayout.createSequentialGroup()
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblBajID)
                        .addGap(46, 46, 46)
                        .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarE)
                            .addGroup(pnlBajasLayout.createSequentialGroup()
                                .addComponent(txtBajID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblAvisoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBajasLayout.createSequentialGroup()
                    .addGap(323, 323, 323)
                    .addComponent(btnEliminar1)
                    .addContainerGap(149, Short.MAX_VALUE)))
        );
        pnlBajasLayout.setVerticalGroup(
            pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBajasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBajID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBajID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarE))
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblAvisoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBajasLayout.createSequentialGroup()
                    .addContainerGap(287, Short.MAX_VALUE)
                    .addComponent(btnEliminar1)
                    .addGap(56, 56, 56)))
        );

        pnlPrincipal.addTab("BAJAS", pnlBajas);

        btnModif.setBackground(new java.awt.Color(255, 255, 255));
        btnModif.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnModif.setText("MODIFICAR");
        btnModif.setEnabled(false);
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });

        btnBuscarM.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarM.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarM.setText("BUSCAR");
        btnBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMActionPerformed(evt);
            }
        });

        lblCamDur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamDur.setText("Duracion");

        lblCamEL.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamEL.setText("Estatus Legal");

        lblCamDis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamDis.setText("Discografia");

        lblAltIDCli1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltIDCli1.setText("ID Cancion:");

        lblIdGen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdGen1.setText("ID Genero:");

        lblCamNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamNom.setText("Nombre");

        txtCamIDC.setEditable(false);
        txtCamIDC.setText("0");
        txtCamIDC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamIDC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamIDCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamIDCKeyTyped(evt);
            }
        });

        txtCamNom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamNomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamNomKeyTyped(evt);
            }
        });

        txtCamDur.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamDur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamDurKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamDurKeyTyped(evt);
            }
        });

        cmbCamEx.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbCamEx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "SI", "NO" }));

        txtCamDisc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamDiscActionPerformed(evt);
            }
        });
        txtCamDisc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamDiscKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamDiscKeyTyped(evt);
            }
        });

        txtCamOy.setEditable(false);
        txtCamOy.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamOy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamOyActionPerformed(evt);
            }
        });
        txtCamOy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamOyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamOyKeyTyped(evt);
            }
        });

        cmbCamEL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbCamEL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--------", "FREEUSE", "COPYRIGHT" }));

        txtCamIDG.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamIDG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamIDGKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamIDGKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCamNom)
                    .addComponent(txtCamIDG, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtCamIDC)
                    .addComponent(cmbCamEx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbCamEL, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCamOy)
                    .addComponent(txtCamDur, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtCamDisc))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtCamIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(txtCamIDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCamNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbCamEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCamDur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCamOy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbCamEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCamDisc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCamExp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamExp.setText("Explicita");

        lblCamOy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamOy.setText("Oyentes");

        lblAvisoIDC1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDC1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoIdGen1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIdGen1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoNombre1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoNombre1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoExplicita1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoExplicita1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoDur1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoDur1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoEL1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoEL1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoDisc1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoDisc1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlAv1Layout = new javax.swing.GroupLayout(pnlAv1);
        pnlAv1.setLayout(pnlAv1Layout);
        pnlAv1Layout.setHorizontalGroup(
            pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAv1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvisoIDC1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoExplicita1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoDur1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoEL1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoDisc1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAv1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblAvisoIdGen1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        pnlAv1Layout.setVerticalGroup(
            pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAv1Layout.createSequentialGroup()
                .addComponent(lblAvisoIDC1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblAvisoNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvisoExplicita1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblAvisoDur1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblAvisoEL1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblAvisoDisc1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAv1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(lblAvisoIdGen1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(228, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlCambiosLayout = new javax.swing.GroupLayout(pnlCambios);
        pnlCambios.setLayout(pnlCambiosLayout);
        pnlCambiosLayout.setHorizontalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnModif))
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCambiosLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAltIDCli1)
                                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                                        .addComponent(lblCamExp)
                                        .addGap(20, 20, 20)))
                                .addGap(31, 31, 31))
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCamDur)
                                    .addComponent(lblCamOy)
                                    .addComponent(lblCamEL)
                                    .addComponent(lblCamDis)
                                    .addComponent(lblCamNom)
                                    .addComponent(lblIdGen1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarM)
                        .addGap(18, 18, 18)
                        .addComponent(pnlAv1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );
        pnlCambiosLayout.setVerticalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(lblAltIDCli1)
                                        .addGap(11, 11, 11)
                                        .addComponent(lblIdGen1)
                                        .addGap(11, 11, 11)
                                        .addComponent(lblCamNom)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCamExp)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCamDur)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCamOy)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCamEL)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblCamDis))
                                    .addComponent(pnlAv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnModif))
                            .addComponent(btnBuscarM))
                        .addContainerGap(27, Short.MAX_VALUE))))
        );

        pnlPrincipal.addTab("CAMBIOS", pnlCambios);

        lblConsIdCan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConsIdCan.setText("ID Cancion:");

        txtConIDCan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtConIDCan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConIDCanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConIDCanKeyTyped(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblAvisoID3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoID3.setForeground(new java.awt.Color(255, 0, 0));

        btnBuscarTds.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarTds.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarTds.setText("MOSTRAR TODOS");
        btnBuscarTds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTdsActionPerformed(evt);
            }
        });

        tblClienteC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_cancion", "id_genero", "nombre", "explicita", "duracion_cancion", "num_oyentes", "estatus_legal", "discografia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblClienteC);

        javax.swing.GroupLayout pnlConsultasLayout = new javax.swing.GroupLayout(pnlConsultas);
        pnlConsultas.setLayout(pnlConsultasLayout);
        pnlConsultasLayout.setHorizontalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblConsIdCan)
                        .addGap(45, 45, 45)
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConIDCan, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlConsultasLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnBuscar)))
                        .addGap(73, 73, 73)
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarTds)
                            .addComponent(lblAvisoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConsultasLayout.setVerticalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConsIdCan)
                        .addComponent(txtConIDCan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAvisoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(btnBuscarTds))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPrincipal.addTab("CONSULTAS", pnlConsultas);

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        pnlPrincipal.addTab("REPORTES", pnlReportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTdsActionPerformed
        Object cancionC[] = new Object[8];
        DAOcanciones cancion = new DAOcanciones();
        ArrayList<Canciones> canciones = null;
         while (c.getRowCount() > 0){
            c.removeRow(0);
        }
            if(c.getRowCount() == 0){
                try {
                    canciones = cancion.select();
                    for (Canciones cnc : canciones) {
                         
                        cancionC[0] =  cnc.getId_cancion();
                        cancionC[1] =  cnc.getId_genero();
                        cancionC[2] =  cnc.getNombre();
                        cancionC[3] =  cnc.getExplicita();
                        cancionC[4] =  cnc.getDuracion_cancion();
                        cancionC[5] =  cnc.getNum_Oyentes();
                        cancionC[6] =  cnc.getEstatus_legal();
                        cancionC[7] =  cnc.getDiscografia();   
                        c.addRow(cancionC);
                    }
                }
                catch (SQLException ex) {
                    ex.printStackTrace(System.out);
                }
            }
            txtConIDCan.setText("");
    }//GEN-LAST:event_btnBuscarTdsActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        boolean encontrado = false;
        idBuscar = Integer.parseInt(txtConIDCan.getText());
        Object cancionM[] = new Object[8];
        DAOcanciones cancion = new DAOcanciones();
        ArrayList<Canciones> canciones = null;
        
            try {
                canciones = cancion.select();
                for (Canciones cnc : canciones) {
                    if(cnc.getId_cancion() == idBuscar){
                        
                        cancionM[0] =  cnc.getId_cancion();
                        cancionM[1] =  cnc.getId_genero();
                        cancionM[2] =  cnc.getNombre();
                        cancionM[3] =  cnc.getExplicita();
                        cancionM[4] =  cnc.getDuracion_cancion();
                        cancionM[5] =  cnc.getNum_Oyentes();
                        cancionM[6] =  cnc.getEstatus_legal();
                        cancionM[7] =  cnc.getDiscografia();
                        
                        encontrado = true;
                        break;
                    }
                }
            }
            catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
            if(encontrado){
                 while (c.getRowCount() > 0){
                    c.removeRow(0);
                }
                if(c.getRowCount() == 0)
                    c.addRow(cancionM);
            }
            else{
                JOptionPane.showMessageDialog(this, "Cancion no encontrada");
            }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtConIDCanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConIDCanKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtConIDCanKeyTyped

    private void txtConIDCanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConIDCanKeyReleased
        habilitarBotonB();
        validarVacios3();
    }//GEN-LAST:event_txtConIDCanKeyReleased

    private void btnBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMActionPerformed
         boolean cancionEncontrada = false;
        idModificar = Integer.parseInt(txtCamIDC.getText());
        Object cancionM[] = new Object[8];
        DAOcanciones cancion = new DAOcanciones();
        ArrayList<Canciones> canciones = null;
        
            try {
                canciones = cancion.select();
                for (Canciones cnc : canciones) {
                    if(cnc.getId_cancion() == idModificar){
                        cancionM[0] =  cnc.getId_cancion();
                        cancionM[1] =  cnc.getId_genero();
                        cancionM[2] =  cnc.getNombre();
                        cancionM[3] =  cnc.getExplicita();
                        cancionM[4] =  cnc.getDuracion_cancion();
                        cancionM[5] =  cnc.getNum_Oyentes();
                        cancionM[6] =  cnc.getEstatus_legal();
                        cancionM[7] =  cnc.getDiscografia();
                        cancionEncontrada = true;
                        break;
                    }
                }
            }
            catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
            if(cancionEncontrada){
                    btnModif.setEnabled(true);
                    habilitarCompMod();
                    agregarElementosModif(cancionM);
            }
            else
                JOptionPane.showMessageDialog(this, "Cancion no encontrada");
    }//GEN-LAST:event_btnBuscarMActionPerformed

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        cancionModID = Integer.parseInt(txtCamIDC.getText());
        int cancionCamIG = Integer.parseInt(txtCamIDG.getText());
        String cancionNombre = txtCamNom.getText();
        String cancionExp = cmbCamEx.getSelectedItem().toString();
        int cancionDur = Integer.parseInt(txtCamDur.getText());
        int cancionNumO = Integer.parseInt(txtCamOy.getText());
        String cancionEL = cmbCamEL.getSelectedItem().toString();
        String cancionDisc = txtCamDisc.getText();

        /*
        1.- Crear una instancia del objeto DAOClientes
        DAOEmpleados empleado = new DAOEmpleados();
        2.- Creamos un nuevo objeto de tipo Cliente
        Empleados empleadosU = new Empleados();
        //Agregamos el ID de la persona que deseamos modificar
        empleadoU.setIdCliente(1);
        empleadoU.setRsCliente("RS");
        //Seteamos los demas parametros
        3.- Ejecutamos
        empleado.update(empleadosU);//Devulve un entero si se aplico el UPDATE, exactamente un 1 porque
        //esa es la cantidad de registros que modifico
        */
        DAOcanciones cancion = new DAOcanciones();
        Canciones cancionU = new Canciones();
        cancionU.setId_cancion(cancionModID);
        cancionU.setId_genero(cancionCamIG);
        cancionU.setNombre(cancionNombre);
        cancionU.setExplicita(cancionExp);
        cancionU.setDuracion_cancion(cancionDur);
        cancionU.setNum_Oyentes(cancionNumO);
        cancionU.setEstatus_legal(cancionEL);
        cancionU.setDiscografia(cancionDisc);
        
        try {
            if(cancion.update(cancionU) != 0){
                JOptionPane.showMessageDialog(this, "Cancion modificada con exito");
                deshabilitarCompMod();
            }
            else
            JOptionPane.showMessageDialog(this, "La canción no se modifico");
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnModifActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        /*DELETE
        1.- Crear una instancia del objeto DAOEmpleados
        DAOempleados empleado = new DAOempleados();
        2.- Creamos un nuevo objeto de tipo Empleados
        Empleados empleadoD = new Empleados();
        3.- Agregamos al objeto persona el ID del empleado a eliminar
        empleadoD.setIdCliente(1);
        4.- Ejecutamos
        empleado.delete(empleadoD);//Devulve un entero si se aplico el DELETE, exactamente un 1 porque
        //esa es la cantidad de registros que elimino
        */
        if(idEliminar != 0){
            DAOcanciones cancion = new DAOcanciones();
            Canciones deleteCancion = new Canciones();
            deleteCancion.setId_cancion(idEliminar);
            try {
                if(cancion.delete(deleteCancion) != 0){
                    JOptionPane.showMessageDialog(this, "Cancion eliminada con exito");
                    txtBajID.setText("");
                    txtBajID.removeAll();
                }
                else
                JOptionPane.showMessageDialog(this, "Hubo un error al eliminar el cancion");
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
        }
        while (e.getRowCount() > 0){
            e.removeRow(0);
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEActionPerformed
         boolean cancionEncontrada = false;
        idEliminar = Integer.parseInt(txtBajID.getText());
        Object cancionE[] = new Object[8];
        DAOcanciones cancion = new DAOcanciones();
        ArrayList<Canciones> cancioness = null;
        

        try {
            cancioness = cancion.select();
            for (Canciones cnc : cancioness) {
                if(cnc.getId_cancion()== idEliminar){
                    cancionE[0] =  cnc.getId_cancion();
                    cancionE[1] =  cnc.getId_genero();
                    cancionE[2] =  cnc.getNombre();
                    cancionE[3] =  cnc.getExplicita();
                    cancionE[4] =  cnc.getDuracion_cancion();
                    cancionE[5] =  cnc.getNum_Oyentes();
                    cancionE[6] =  cnc.getEstatus_legal();
                    cancionE[7] =  cnc.getDiscografia();
                    cancionEncontrada = true;
                    break;
                }
            }
        }
        catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        while (e.getRowCount() > 0){
            e.removeRow(0);
        }
        if(cancionEncontrada){

            if(e.getRowCount() == 0){
                e.addRow(cancionE);
                btnEliminar1.setEnabled(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Cancion no encontrada");
        }
    }//GEN-LAST:event_btnBuscarEActionPerformed

    private void txtBajIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBajIDKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtBajIDKeyTyped

    private void txtBajIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBajIDKeyReleased
        habilitarBotonE();
        validarVacios2();
    }//GEN-LAST:event_txtBajIDKeyReleased

    private void txtAltDurKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltDurKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltDurKeyTyped

    private void txtAltDurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltDurKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltDurKeyReleased

    private void txtAltDurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltDurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltDurActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int idCan = Integer.parseInt(txtAltIDC.getText());
        
        int idGen =Integer.parseInt(txtAltIdGen.getText());
        String nombre = txtAltNombre.getText();
        String explicita = cmbAltExp.getSelectedItem().toString();
        int duracion =Integer.parseInt(txtAltDur.getText());
        int num_oyentes=Integer.parseInt(txtAltOy.getText());
        String estatuslegal = cmbAltEL.getSelectedItem().toString();
        String discografia = txtAltDisc.getText();

        //        emailCliente,passwordCliente,rsCliente,rfcCLiente,domicilioCliente,cdfiCliente
        //Canciones(id_cancion,id_genero,nombre,explicita,duracion_cancion,num_oyentes,estatus_legal,discografia);
        //insertarCancion(int id_cancion, int id_genero, String nombre, String explicita, int duracion_cancion, int num_oyentes, String estatus_legal, String discografia)
        insertarCancion(idCan,idGen,nombre,explicita,duracion,num_oyentes,estatuslegal,discografia);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtAltDiscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltDiscKeyTyped
        validarCaracter(evt);
    }//GEN-LAST:event_txtAltDiscKeyTyped

    private void txtAltDiscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltDiscKeyReleased
        habilitarBoton();
        validarVacios();
    }//GEN-LAST:event_txtAltDiscKeyReleased

    private void txtAltDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltDiscActionPerformed

    private void txtAltNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltNombreKeyTyped
       validarCaracter(evt);
    }//GEN-LAST:event_txtAltNombreKeyTyped

    private void txtAltNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltNombreKeyReleased
       habilitarBoton();
        validarVacios();
    }//GEN-LAST:event_txtAltNombreKeyReleased

    private void txtAltIdGenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltIdGenKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtAltIdGenKeyTyped

    private void txtAltIdGenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltIdGenKeyReleased
        habilitarBoton();
        validarVacios();
    }//GEN-LAST:event_txtAltIdGenKeyReleased

     private void txtAltIDCKeyReleased(java.awt.event.KeyEvent evt) {                                   
       validarNumeros(evt);
    }  
    private void txtAltIDCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltIDCKeyTyped
       validarNumeros(evt);
    }//GEN-LAST:event_txtAltIDCKeyTyped

//GEN-FIRST:event_txtAltIDCKeyReleased
 
//GEN-LAST:event_txtAltIDCKeyReleased

    private void txtAltOyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltOyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltOyActionPerformed

    private void txtAltOyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltOyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltOyKeyReleased

    private void txtAltOyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltOyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltOyKeyTyped

    private void txtCamIDCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDCKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamIDCKeyReleased

    private void txtCamIDCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDCKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamIDCKeyTyped

    private void txtCamNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamNomKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamNomKeyReleased

    private void txtCamNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamNomKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamNomKeyTyped

    private void txtCamDurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamDurKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamDurKeyReleased

    private void txtCamDurKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamDurKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamDurKeyTyped

    private void txtCamDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamDiscActionPerformed

    private void txtCamDiscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamDiscKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamDiscKeyReleased

    private void txtCamDiscKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamDiscKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamDiscKeyTyped

    private void txtCamOyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamOyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamOyActionPerformed

    private void txtCamOyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamOyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamOyKeyReleased

    private void txtCamOyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamOyKeyTyped
        
    }//GEN-LAST:event_txtCamOyKeyTyped

    private void txtCamIDGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDGKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtCamIDGKeyTyped

    private void txtCamIDGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDGKeyReleased
        habilitarBotonM();
        validarVacios1();
    }//GEN-LAST:event_txtCamIDGKeyReleased

   
     public void validarVacios(){
        if(txtAltIDC.getText().isEmpty()){
            lblAvisoIDC.setText("Campo obligatorio");
        }else{
            lblAvisoIDC.setText("");
        }
        if(txtAltIdGen.getText().isEmpty()){
            lblAvisoIdGen.setText("Campo obligatorio");
        }else{
            lblAvisoIdGen.setText("");
        }
        if(txtAltNombre.getText().isEmpty()){
            lblAvisoNombre.setText("Campo obligatorio");
        }else{
            lblAvisoNombre.setText("");
        }
        if(cmbAltExp.getSelectedItem().toString().equals(0)){
            lblAvisoExplicita.setText("Campo obligatorio");
        }else{
            lblAvisoExplicita.setText("");
        }
        if(txtAltDur.getText().isEmpty()){
            lblAvisoDur.setText("Campo obligatorio");
        }else{
            lblAvisoDur.setText("");
        }
        if(cmbAltEL.getSelectedItem().toString().equals(0)){
            lblAvisoEL.setText("Campo obligatorio");
        }else{
            lblAvisoEL.setText("");
        }
        if(txtAltDisc.getText().isEmpty()){
            lblAvisoDisc.setText("Campo obligatorio");
        }else{
            lblAvisoDisc.setText("");
        }
    }
     
     public void validarVacios1(){
        if(txtCamIDC.getText().isEmpty()){
            lblAvisoIDC1.setText("Campo obligatorio");
        }else{
            lblAvisoIDC1.setText("");
        }
        if(txtCamIDG.getText().isEmpty()){
            lblAvisoIdGen1.setText("Campo obligatorio");
        }else{
            lblAvisoIdGen1.setText("");
        }
        if(txtCamNom.getText().isEmpty()){
            lblAvisoNombre1.setText("Campo obligatorio");
        }else{
            lblAvisoNombre1.setText("");
        }
        if(cmbCamEx.getSelectedItem().toString().equals(0)){
            lblAvisoExplicita1.setText("Campo obligatorio");
        }else{
            lblAvisoExplicita1.setText("");
        }
        if(txtCamDur.getText().isEmpty()){
            lblAvisoDur1.setText("Campo obligatorio");
        }else{
            lblAvisoDur1.setText("");
        }
        if(cmbCamEL.getSelectedItem().toString().equals(0)){
            lblAvisoEL1.setText("Campo obligatorio");
        }else{
            lblAvisoEL1.setText("");
        }
        if(txtCamDisc.getText().isEmpty()){
            lblAvisoDisc1.setText("Campo obligatorio");
        }else{
            lblAvisoDisc1.setText("");
        }
    }
    public void validarVacios2(){
        if(txtBajID.getText().isEmpty()){
            lblAvisoID2.setText("ID obligatorio");
        }else{
            lblAvisoID2.setText("");
        }
    }
    
    public void validarVacios3(){
        if(txtConIDCan.getText().isEmpty()){
            lblAvisoID3.setText("ID obligatorio");
        }else{
            lblAvisoID3.setText("");
        }
    }
          
    public void validarNumeros(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()>=32 && evento.getKeyChar()<=47
                ||evento.getKeyChar()>=58 && evento.getKeyChar()<=255){
            evento.consume();
            JOptionPane.showMessageDialog(this,"Solo Numeros");
        }
    }
    
    public void habilitarBoton(){
        if(txtAltIDC.getText().isEmpty() 
                || txtAltIdGen.getText().isEmpty() 
                || txtAltNombre.getText().isEmpty() 
                || cmbAltExp.getSelectedItem().equals(0) 
                || txtAltDisc.getText().isEmpty()
                || cmbAltEL.getSelectedItem().equals(0)
                || txtAltDur.getText().isEmpty()){
            btnAgregar.setEnabled(false);
        }else{
            btnAgregar.setEnabled(true);
        }
    }
    
    public void habilitarBotonM(){
        if(txtCamIDC.getText().isEmpty() 
                || txtCamIDG.getText().isEmpty() 
                || txtCamNom.getText().isEmpty() 
                || cmbCamEx.getSelectedItem().equals(0) 
                || txtCamDur.getText().isEmpty()
                || cmbCamEL.getSelectedItem().equals(0)
                || txtCamDisc.getText().isEmpty()){
            btnModif.setEnabled(false);
        }else{
            btnModif.setEnabled(true);
        }
    }
    
    public void habilitarBotonE(){
        if(txtBajID.getText().isEmpty()){
            btnBuscarE.setEnabled(false);
        }else{
            btnBuscarE.setEnabled(true);
        }
    }
    
    public void habilitarBotonB(){
        if(txtConIDCan.getText().isEmpty()){
            btnBuscar.setEnabled(false);
        }else{
            btnBuscar.setEnabled(true);
        }
    }
    
    public void validarCaracter(java.awt.event.KeyEvent evento){
        if(evento.getKeyChar()>=33 && evento.getKeyChar()<=64 
                || evento.getKeyChar()>=91 && evento.getKeyChar()<=96
                || evento.getKeyChar()>=123 && evento.getKeyChar()<=208
                || evento.getKeyChar()>=210 && evento.getKeyChar()<=240
                || evento.getKeyChar()>=242 && evento.getKeyChar()<=255){
            evento.consume();
            JOptionPane.showMessageDialog(this,"No se permiten caracteres especiales");
        }
    }
    
    private void insertarCancion(int id_cancion, int id_genero, String nombre, String explicita, int duracion_cancion, int num_oyentes, String estatus_legal, String discografia){
        /*INSERT
        1.- Crear una instancia del objeto DAOclientes
                DAOempleados nuevoEmpleado = new DAOempleados();
        2.- Creamos un nuevo objeto de tipo Empleados
                Empleados empleadoI = new Empleados();
                agregamos cada dato a empleadoI
                empleadoI.setRsCliente("");
                //o un constructor que inicialice todo
        3.- Una vez que se llenan los datos para el objeto empleadoI, ejecutar
                nuevoEmpleado.insert(empleadoI); //Devulve un entero si se aplico el INSERT, exactamente un 1 porque
                                        //esa es la cantidad de registros que inserto
        */
        
        DAOcanciones nuevaCancion = new DAOcanciones();
        Canciones cancion = new Canciones(id_cancion,id_genero,nombre,explicita,duracion_cancion,num_oyentes,estatus_legal,discografia);
        try {
            if(nuevaCancion.insert(cancion) != 0)
                JOptionPane.showMessageDialog(this,"Cancion dada de alta con exito");
            else
                JOptionPane.showMessageDialog(this,"La cancion no pudo ser dada de alta");
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarE;
    private javax.swing.JButton btnBuscarM;
    private javax.swing.JButton btnBuscarTds;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModif;
    private javax.swing.JComboBox<String> cmbAltEL;
    private javax.swing.JComboBox<String> cmbAltExp;
    private javax.swing.JComboBox<String> cmbCamEL;
    private javax.swing.JComboBox<String> cmbCamEx;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAltDur;
    private javax.swing.JLabel lblAltExp;
    private javax.swing.JLabel lblAltIDCli;
    private javax.swing.JLabel lblAltIDCli1;
    private javax.swing.JLabel lblAltOy;
    private javax.swing.JLabel lblAltOy1;
    private javax.swing.JLabel lblAltRFC;
    private javax.swing.JLabel lblAvisoDisc;
    private javax.swing.JLabel lblAvisoDisc1;
    private javax.swing.JLabel lblAvisoDur;
    private javax.swing.JLabel lblAvisoDur1;
    private javax.swing.JLabel lblAvisoEL;
    private javax.swing.JLabel lblAvisoEL1;
    private javax.swing.JLabel lblAvisoExplicita;
    private javax.swing.JLabel lblAvisoExplicita1;
    private javax.swing.JLabel lblAvisoID2;
    private javax.swing.JLabel lblAvisoID3;
    private javax.swing.JLabel lblAvisoIDC;
    private javax.swing.JLabel lblAvisoIDC1;
    private javax.swing.JLabel lblAvisoIdGen;
    private javax.swing.JLabel lblAvisoIdGen1;
    private javax.swing.JLabel lblAvisoNombre;
    private javax.swing.JLabel lblAvisoNombre1;
    private javax.swing.JLabel lblBajID;
    private javax.swing.JLabel lblCamDis;
    private javax.swing.JLabel lblCamDur;
    private javax.swing.JLabel lblCamEL;
    private javax.swing.JLabel lblCamExp;
    private javax.swing.JLabel lblCamNom;
    private javax.swing.JLabel lblCamOy;
    private javax.swing.JLabel lblConsIdCan;
    private javax.swing.JLabel lblCorr1;
    private javax.swing.JLabel lblIdGen;
    private javax.swing.JLabel lblIdGen1;
    private javax.swing.JPanel pnlAltas;
    private javax.swing.JPanel pnlAv;
    private javax.swing.JPanel pnlAv1;
    private javax.swing.JPanel pnlBajas;
    private javax.swing.JPanel pnlCambios;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JTabbedPane pnlPrincipal;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JTable tblClienteC;
    private javax.swing.JTable tblClienteE;
    private javax.swing.JTextField txtAltDisc;
    private javax.swing.JTextField txtAltDur;
    private javax.swing.JTextField txtAltIDC;
    private javax.swing.JTextField txtAltIdGen;
    private javax.swing.JTextField txtAltNombre;
    private javax.swing.JTextField txtAltOy;
    private javax.swing.JTextField txtBajID;
    private javax.swing.JTextField txtCamDisc;
    private javax.swing.JTextField txtCamDur;
    private javax.swing.JTextField txtCamIDC;
    private javax.swing.JTextField txtCamIDG;
    private javax.swing.JTextField txtCamNom;
    private javax.swing.JTextField txtCamOy;
    private javax.swing.JTextField txtConIDCan;
    // End of variables declaration//GEN-END:variables
    private int idEliminar = 0, idModificar = 0,cancionModID = 0, idBuscar = 0;
    private void agregarElementosModif(Object[] cancionM) {
//       id_cancion,id_genero,nombre,explicita,duracion_cancion,num_oyentes,estatus_legal,discografia
       txtCamIDC.setText(cancionM[0].toString());
        txtCamIDG.setText(cancionM[1].toString());
        txtCamNom.setText(cancionM[2].toString());
        cmbCamEx.setSelectedItem(cancionM[3].toString());
        txtCamDur.setText(cancionM[4].toString());
        txtCamOy.setText(cancionM[5].toString());
        cmbCamEL.setSelectedItem(cancionM[6].toString());
        txtCamDisc.setText(cancionM[7].toString());       
    }
    
   private void habilitarCompMod(){
        txtCamIDC.setEditable(true);
        txtCamNom.setEditable(true);
        cmbCamEx.setEditable(true);
        txtCamDur.setEditable(true);
        txtCamOy.setEditable(true);
        cmbCamEL.setEditable(true);
        txtCamDisc.setEditable(true);
    }
    private void deshabilitarCompMod(){
        txtCamIDC.setEditable(true);
        txtCamNom.setEditable(true);
        cmbCamEx.setEditable(true);
        txtCamDur.setEditable(true);
        txtCamOy.setEditable(true);
        cmbCamEL.setEditable(true);
        txtCamDisc.setEditable(true);
    }
}
