package gui;

import dao.DAOcategorias;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Categorias;

public class DlgCategorias extends javax.swing.JDialog {

    DefaultTableModel e, c;

    public DlgCategorias(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setResizable(false);
        initComponents();
        e = (DefaultTableModel) tblClienteE.getModel();
        c = (DefaultTableModel) tblClienteC.getModel();
        //BOTON AGREGAR
        ImageIcon icagre = new ImageIcon(getClass().getResource("/Imagenes/agregar.png"));
        Icon iconoagre = new ImageIcon(icagre.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnAgregar.setIcon(iconoagre);
        //BOTON ELIMINAR
        ImageIcon icelim = new ImageIcon(getClass().getResource("/Imagenes/eliminar.png"));
        Icon iconoelim = new ImageIcon(icelim.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnBuscarE.setIcon(iconoelim);
        //BOTON BUSCAR
        ImageIcon icbuscar = new ImageIcon(getClass().getResource("/Imagenes/buscar.png"));
        Icon iconobuscar = new ImageIcon(icbuscar.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnBuscar.setIcon(iconobuscar);
        //BOTON MODIFICAR
        ImageIcon icmodif = new ImageIcon(getClass().getResource("/Imagenes/edit.png"));
        Icon iconomodif = new ImageIcon(icmodif.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnModif.setIcon(iconomodif);
        //Deshabilitar botones
        btnAgregar.setEnabled(false);
        btnBuscarE.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnModif.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JTabbedPane();
        pnlAltas = new javax.swing.JPanel();
        lblAltIDCli = new javax.swing.JLabel();
        lblAltTipoC = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtAltIDCat = new javax.swing.JTextField();
        txtAltTipoC = new javax.swing.JTextField();
        pnlAv = new javax.swing.JPanel();
        lblAvisoIDCat = new javax.swing.JLabel();
        lblAvisoTipoc = new javax.swing.JLabel();
        pnlBajas = new javax.swing.JPanel();
        lblBajID = new javax.swing.JLabel();
        txtBajID = new javax.swing.JTextField();
        btnBuscarE = new javax.swing.JButton();
        lblAvisoID2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClienteE = new javax.swing.JTable();
        btnEliminar1 = new javax.swing.JButton();
        pnlCambios = new javax.swing.JPanel();
        btnModif = new javax.swing.JButton();
        btnBuscarM = new javax.swing.JButton();
        lblAltIDCli1 = new javax.swing.JLabel();
        lblCamNom = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtCamIDC = new javax.swing.JTextField();
        txtCamTC = new javax.swing.JTextField();
        lblAvisoTipoc1 = new javax.swing.JLabel();
        lblAvisoIDC = new javax.swing.JLabel();
        pnlAv1 = new javax.swing.JPanel();
        lblAvisoIDCat1 = new javax.swing.JLabel();
        lblAvisoTC = new javax.swing.JLabel();
        pnlConsultas = new javax.swing.JPanel();
        lblConsIdCan = new javax.swing.JLabel();
        txtConIDCat = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblAvisoID3 = new javax.swing.JLabel();
        btnBuscarTds = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClienteC = new javax.swing.JTable();
        pnlReportes = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CATEGORIAS");

        pnlPrincipal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblAltIDCli.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltIDCli.setText("ID Categoria:");

        lblAltTipoC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltTipoC.setText("Tipo de contenido");

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtAltIDCat.setEditable(false);
        txtAltIDCat.setText("0");
        txtAltIDCat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltIDCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltIDCatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltIDCatKeyTyped(evt);
            }
        });

        txtAltTipoC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltTipoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltTipoCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltTipoCKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAltIDCat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAltTipoC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtAltIDCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltTipoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        lblAvisoIDCat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDCat.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoTipoc.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoTipoc.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlAvLayout = new javax.swing.GroupLayout(pnlAv);
        pnlAv.setLayout(pnlAvLayout);
        pnlAvLayout.setHorizontalGroup(
            pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvisoIDCat, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoTipoc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAvLayout.setVerticalGroup(
            pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvLayout.createSequentialGroup()
                .addComponent(lblAvisoIDCat, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAvisoTipoc, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAltasLayout = new javax.swing.GroupLayout(pnlAltas);
        pnlAltas.setLayout(pnlAltasLayout);
        pnlAltasLayout.setHorizontalGroup(
            pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlAltasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAgregar))
                    .addGroup(pnlAltasLayout.createSequentialGroup()
                        .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAltTipoC)
                            .addComponent(lblAltIDCli))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(pnlAv, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        pnlAltasLayout.setVerticalGroup(
            pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAltasLayout.createSequentialGroup()
                        .addComponent(lblAltIDCli)
                        .addGap(17, 17, 17)
                        .addComponent(lblAltTipoC))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnAgregar)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("ALTAS", pnlAltas);

        lblBajID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBajID.setText("ID Categoria:");

        txtBajID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtBajID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBajIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBajIDKeyTyped(evt);
            }
        });

        btnBuscarE.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarE.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarE.setText("BUSCAR");
        btnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEActionPerformed(evt);
            }
        });

        lblAvisoID2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoID2.setForeground(new java.awt.Color(255, 0, 0));

        tblClienteE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_genero", "no_oyentes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblClienteE);

        btnEliminar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.setEnabled(false);
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBajasLayout = new javax.swing.GroupLayout(pnlBajas);
        pnlBajas.setLayout(pnlBajasLayout);
        pnlBajasLayout.setHorizontalGroup(
            pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBajasLayout.createSequentialGroup()
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBajasLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lblBajID)
                                .addGap(46, 46, 46)
                                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarE)
                                    .addGroup(pnlBajasLayout.createSequentialGroup()
                                        .addComponent(txtBajID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(lblAvisoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlBajasLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBajasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEliminar1)))
                .addContainerGap())
        );
        pnlBajasLayout.setVerticalGroup(
            pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBajasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBajID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBajID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarE))
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblAvisoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnEliminar1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("BAJAS", pnlBajas);

        btnModif.setBackground(new java.awt.Color(255, 255, 255));
        btnModif.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnModif.setText("MODIFICAR");
        btnModif.setEnabled(false);
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });

        btnBuscarM.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarM.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarM.setText("BUSCAR");
        btnBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMActionPerformed(evt);
            }
        });

        lblAltIDCli1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltIDCli1.setText("ID Categoria:");

        lblCamNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamNom.setText("Tipo de Contenido");

        txtCamIDC.setEditable(false);
        txtCamIDC.setText("0");
        txtCamIDC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamIDC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamIDCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamIDCKeyTyped(evt);
            }
        });

        txtCamTC.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamTC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamTCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamTCKeyTyped(evt);
            }
        });

        lblAvisoTipoc1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoTipoc1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoIDC.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDC.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCamTC)
                    .addComponent(txtCamIDC, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvisoTipoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblAvisoIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAvisoTipoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtCamIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCamTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        lblAvisoIDCat1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDCat1.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoTC.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoTC.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlAv1Layout = new javax.swing.GroupLayout(pnlAv1);
        pnlAv1.setLayout(pnlAv1Layout);
        pnlAv1Layout.setHorizontalGroup(
            pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAv1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvisoIDCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAv1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lblAvisoTC, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(553, Short.MAX_VALUE)))
        );
        pnlAv1Layout.setVerticalGroup(
            pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAv1Layout.createSequentialGroup()
                .addComponent(lblAvisoIDCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAv1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(lblAvisoTC, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlCambiosLayout = new javax.swing.GroupLayout(pnlCambios);
        pnlCambios.setLayout(pnlCambiosLayout);
        pnlCambiosLayout.setHorizontalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblAltIDCli1)
                        .addGap(31, 31, 31))
                    .addComponent(lblCamNom))
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addComponent(btnBuscarM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlAv1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnModif))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCambiosLayout.setVerticalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblAltIDCli1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCamNom)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addComponent(pnlAv1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(83, 83, 83))
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarM)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(btnModif)
                        .addGap(73, 73, 73))))
        );

        pnlPrincipal.addTab("CAMBIOS", pnlCambios);

        lblConsIdCan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConsIdCan.setText("ID Categoria:");

        txtConIDCat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtConIDCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConIDCatKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConIDCatKeyTyped(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblAvisoID3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoID3.setForeground(new java.awt.Color(255, 0, 0));

        btnBuscarTds.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarTds.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarTds.setText("MOSTRAR TODOS");
        btnBuscarTds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTdsActionPerformed(evt);
            }
        });

        tblClienteC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_genero", "no_oyentes"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblClienteC);

        javax.swing.GroupLayout pnlConsultasLayout = new javax.swing.GroupLayout(pnlConsultas);
        pnlConsultas.setLayout(pnlConsultasLayout);
        pnlConsultasLayout.setHorizontalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblConsIdCan)
                        .addGap(45, 45, 45)
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConIDCat, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlConsultasLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnBuscar)))
                        .addGap(73, 73, 73)
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarTds)
                            .addComponent(lblAvisoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConsultasLayout.setVerticalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConsIdCan)
                        .addComponent(txtConIDCat, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAvisoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(btnBuscarTds))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("CONSULTAS", pnlConsultas);

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        pnlPrincipal.addTab("REPORTES", pnlReportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 354, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTdsActionPerformed
        Object categoriaC[] = new Object[2];
        DAOcategorias categoria = new DAOcategorias();
        ArrayList<Categorias> categorias = null;
        while (c.getRowCount() > 0) {
            c.removeRow(0);
        }
        if (c.getRowCount() == 0) {
            try {
                categorias = categoria.select();
                for (Categorias cat : categorias) {

                    categoriaC[0] = cat.getId_categoria();
                    categoriaC[1] = cat.getTipo_contenido();

                    c.addRow(categoriaC);
                }
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
        }
        txtConIDCat.setText("");
    }//GEN-LAST:event_btnBuscarTdsActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        boolean encontrado = false;
        idBuscar = Integer.parseInt(txtConIDCat.getText());
        Object categoriaM[] = new Object[2];
        DAOcategorias categoria = new DAOcategorias();
        ArrayList<Categorias> categorias = null;

        try {
            categorias = categoria.select();
            for (Categorias cat : categorias) {
                if (cat.getId_categoria() == idBuscar) {

                    categoriaM[0] = cat.getId_categoria();
                    categoriaM[1] = cat.getTipo_contenido();

                    encontrado = true;
                    break;
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        if (encontrado) {
            while (c.getRowCount() > 0) {
                c.removeRow(0);
            }
            if (c.getRowCount() == 0) {
                c.addRow(categoriaM);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Categoria no encontrada");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtConIDCatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConIDCatKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtConIDCatKeyTyped

    private void txtConIDCatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConIDCatKeyReleased
        habilitarBotonB();
        validarVacios3();
    }//GEN-LAST:event_txtConIDCatKeyReleased

    private void btnBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMActionPerformed
        boolean categoriaEncontrada = false;
        idModificar = Integer.parseInt(txtCamIDC.getText());
        Object categoriaM[] = new Object[2];
        DAOcategorias categoria = new DAOcategorias();
        ArrayList<Categorias> categorias = null;

        try {
            categorias = categoria.select();
            for (Categorias cat : categorias) {
                if (cat.getId_categoria() == idModificar) {
                    categoriaM[0] = cat.getId_categoria();
                    categoriaM[1] = cat.getTipo_contenido();
                    categoriaEncontrada = true;
                    break;
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        if (categoriaEncontrada) {
            btnModif.setEnabled(true);
            habilitarCompMod();
            agrgarElementosModif(categoriaM);
        } else
            JOptionPane.showMessageDialog(this, "Categoria no encontrada");
    }//GEN-LAST:event_btnBuscarMActionPerformed

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed

        categoriaModID = Integer.parseInt(txtCamIDC.getText());
        String categoriaModTipo_contenido = txtCamTC.getText();

        DAOcategorias categoria = new DAOcategorias();
        Categorias categoriaU = new Categorias();
        categoriaU.setId_categoria(categoriaModID);
        categoriaU.setTipo_contenido(categoriaModTipo_contenido);

        try {
            if (categoria.update(categoriaU) != 0) {
                JOptionPane.showMessageDialog(this, "Categoria modificada con exito");
                deshabilitarCompMod();
            } else {
                JOptionPane.showMessageDialog(this, "La categoria no se modifico");
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnModifActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed

        if (idEliminar != 0) {
            DAOcategorias categoria = new DAOcategorias();
            Categorias deleteCategoria = new Categorias();
            deleteCategoria.setId_categoria(idEliminar);
            try {
                if (categoria.delete(deleteCategoria) != 0) {
                    JOptionPane.showMessageDialog(this, "Categoria eliminada con exito");
                    txtBajID.setText("");
                    txtBajID.removeAll();
                } else {
                    JOptionPane.showMessageDialog(this, "Hubo un error al eliminar la categoria");
                }
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
        }
        while (e.getRowCount() > 0) {
            e.removeRow(0);
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEActionPerformed
        boolean categoriaEncontrada = false;
        idEliminar = Integer.parseInt(txtBajID.getText());
        Object categoriaE[] = new Object[2];
        DAOcategorias categoria = new DAOcategorias();
        ArrayList<Categorias> categoriass = null;

        try {
            categoriass = categoria.select();
            for (Categorias cat : categoriass) {
                if (cat.getId_categoria() == idEliminar) {
                    categoriaE[0] = cat.getId_categoria();
                    categoriaE[1] = cat.getTipo_contenido();
                    categoriaEncontrada = true;
                    break;
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        while (e.getRowCount() > 0) {
            e.removeRow(0);
        }
        if (categoriaEncontrada) {

            if (e.getRowCount() == 0) {
                e.addRow(categoriaE);
                btnEliminar1.setEnabled(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Categoria no encontrada");
        }
    }//GEN-LAST:event_btnBuscarEActionPerformed

    private void txtBajIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBajIDKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtBajIDKeyTyped

    private void txtBajIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBajIDKeyReleased
        habilitarBotonE();
        validarVacios2();
    }//GEN-LAST:event_txtBajIDKeyReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int idcategoria = Integer.parseInt(txtAltIDCat.getText());
        String tipocontenido = txtAltTipoC.getText();

        //        emailCliente,passwordCliente,rsCliente,rfcCLiente,domicilioCliente,cdfiCliente
        insertarCategoria(idcategoria, tipocontenido);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtAltIDCKeyReleased(java.awt.event.KeyEvent evt) {
        validarNumeros(evt);
    }
    private void txtCamIDCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDCKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamIDCKeyReleased

    private void txtCamIDCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDCKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamIDCKeyTyped

    private void txtCamTCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamTCKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamTCKeyReleased

    private void txtCamTCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamTCKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamTCKeyTyped

    private void txtAltTipoCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltTipoCKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtAltTipoCKeyTyped

    private void txtAltTipoCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltTipoCKeyReleased
        habilitarBoton();
        validarVacios();
    }//GEN-LAST:event_txtAltTipoCKeyReleased

    private void txtAltIDCatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltIDCatKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtAltIDCatKeyTyped

    private void txtAltIDCKeyTyped(java.awt.event.KeyEvent evt) {
        validarNumeros(evt);
    }

    private void txtAltIDCatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltIDCatKeyReleased

    }//GEN-LAST:event_txtAltIDCatKeyReleased
    public void validarVacios() {
        if (txtAltIDCat.getText().isEmpty()) {
            lblAvisoIDCat.setText("Campo obligatorio");
        } else {
            lblAvisoIDCat.setText("");
        }
        if (txtAltTipoC.getText().isEmpty()) {
            lblAvisoTipoc.setText("Campo obligatorio");
        } else {
            lblAvisoTipoc.setText("");
        }
    }

    public void validarVacios1() {
        if (txtCamIDC.getText().isEmpty()) {
            lblAvisoIDC.setText("Campo obligatorio");
        } else {
            lblAvisoIDC.setText("");
        }
        if (txtCamTC.getText().isEmpty()) {
            lblAvisoTipoc1.setText("Campo obligatorio");
        } else {
            lblAvisoTipoc1.setText("");
        }

        /*if (txtModCorr.getText().isEmpty()) {
            lblAvisoCorr1.setText("Campo obligatorio");
        } else if (!txtModCorr.getText().contains("@")
                || !txtModCorr.getText().contains(".")) {
            lblAvisoCorr1.setText("Correo NO valido");
        } else {
            lblAvisoCorr1.setText("");
        }*/
    }

    public void validarVacios2() {
        if (txtBajID.getText().isEmpty()) {
            lblAvisoID2.setText("ID obligatorio");
        } else {
            lblAvisoID2.setText("");
        }
    }

    public void validarVacios3() {
        if (txtConIDCat.getText().isEmpty()) {
            lblAvisoID3.setText("ID obligatorio");
        } else {
            lblAvisoID3.setText("");
        }
    }

    public void validarNumeros(java.awt.event.KeyEvent evento) {
        if (evento.getKeyChar() >= 32 && evento.getKeyChar() <= 47
                || evento.getKeyChar() >= 58 && evento.getKeyChar() <= 255) {
            evento.consume();
            JOptionPane.showMessageDialog(this, "Solo Numeros");
        }
    }

    public void habilitarBoton() {
        if (txtAltIDCat.getText().isEmpty()
                || txtAltTipoC.getText().isEmpty()) {
            btnAgregar.setEnabled(false);
        } else {
            btnAgregar.setEnabled(true);
        }
    }

    public void habilitarBotonM() {
        if (txtAltIDCat.getText().isEmpty()
                || txtAltTipoC.getText().isEmpty()) {
            btnModif.setEnabled(false);
        } else {
            btnModif.setEnabled(true);
        }
    }

    public void habilitarBotonE() {
        if (txtBajID.getText().isEmpty()) {
            btnBuscarE.setEnabled(false);
        } else {
            btnBuscarE.setEnabled(true);
        }
    }

    public void habilitarBotonB() {
        if (txtConIDCat.getText().isEmpty()) {
            btnBuscar.setEnabled(false);
        } else {
            btnBuscar.setEnabled(true);
        }
    }

    public void validarCaracter(java.awt.event.KeyEvent evento) {
        if (evento.getKeyChar() >= 33 && evento.getKeyChar() <= 64
                || evento.getKeyChar() >= 91 && evento.getKeyChar() <= 96
                || evento.getKeyChar() >= 123 && evento.getKeyChar() <= 208
                || evento.getKeyChar() >= 210 && evento.getKeyChar() <= 240
                || evento.getKeyChar() >= 242 && evento.getKeyChar() <= 255) {
            evento.consume();
            JOptionPane.showMessageDialog(this, "No se permiten caracteres especiales");
        }
    }

    private void insertarCategoria(int id_categoria, String tipo_contenido) {

        DAOcategorias nuevaCategoria = new DAOcategorias();
        Categorias categoria = new Categorias(id_categoria, tipo_contenido);
        try {
            if (nuevaCategoria.insert(categoria) != 0) {
                JOptionPane.showMessageDialog(this, "Categoria dada de alta con exito");
            } else {
                JOptionPane.showMessageDialog(this, "La Categoria no pudo ser dada de alta");
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarE;
    private javax.swing.JButton btnBuscarM;
    private javax.swing.JButton btnBuscarTds;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModif;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAltIDCli;
    private javax.swing.JLabel lblAltIDCli1;
    private javax.swing.JLabel lblAltTipoC;
    private javax.swing.JLabel lblAvisoID2;
    private javax.swing.JLabel lblAvisoID3;
    private javax.swing.JLabel lblAvisoIDC;
    private javax.swing.JLabel lblAvisoIDCat;
    private javax.swing.JLabel lblAvisoIDCat1;
    private javax.swing.JLabel lblAvisoTC;
    private javax.swing.JLabel lblAvisoTipoc;
    private javax.swing.JLabel lblAvisoTipoc1;
    private javax.swing.JLabel lblBajID;
    private javax.swing.JLabel lblCamNom;
    private javax.swing.JLabel lblConsIdCan;
    private javax.swing.JPanel pnlAltas;
    private javax.swing.JPanel pnlAv;
    private javax.swing.JPanel pnlAv1;
    private javax.swing.JPanel pnlBajas;
    private javax.swing.JPanel pnlCambios;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JTabbedPane pnlPrincipal;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JTable tblClienteC;
    private javax.swing.JTable tblClienteE;
    private javax.swing.JTextField txtAltIDCat;
    private javax.swing.JTextField txtAltTipoC;
    private javax.swing.JTextField txtBajID;
    private javax.swing.JTextField txtCamIDC;
    private javax.swing.JTextField txtCamTC;
    private javax.swing.JTextField txtConIDCat;
    // End of variables declaration//GEN-END:variables
    private int idEliminar = 0, idModificar = 0, categoriaModID = 0, idBuscar = 0;

    private void agrgarElementosModif(Object[] categoriaM) {
        //emailCliente,passwordCliente,rsCliente,rfcCLiente,domicilioCliente,cdfiCliente 
        txtCamIDC.setText(categoriaM[1].toString());
        txtCamTC.setText(categoriaM[2].toString());
    }

    private void habilitarCompMod() {
        txtCamIDC.setEditable(true);
        txtCamTC.setEditable(true);

    }

    private void deshabilitarCompMod() {
        txtCamIDC.setEditable(false);
        txtCamTC.setEditable(false);
    }
}
