package gui;

import dao.DAOgeneros;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Generos;

public class DlgGeneros extends javax.swing.JDialog {

    DefaultTableModel e, c;

    public DlgGeneros(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setResizable(false);
        initComponents();
        e = (DefaultTableModel) tblClienteE.getModel();
        c = (DefaultTableModel) tblClienteC.getModel();
        //BOTON AGREGAR
        ImageIcon icagre = new ImageIcon(getClass().getResource("/Imagenes/agregar.png"));
        Icon iconoagre = new ImageIcon(icagre.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnAgregar.setIcon(iconoagre);
        //BOTON ELIMINAR
        ImageIcon icelim = new ImageIcon(getClass().getResource("/Imagenes/eliminar.png"));
        Icon iconoelim = new ImageIcon(icelim.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnBuscarE.setIcon(iconoelim);
        //BOTON BUSCAR
        ImageIcon icbuscar = new ImageIcon(getClass().getResource("/Imagenes/buscar.png"));
        Icon iconobuscar = new ImageIcon(icbuscar.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnBuscar.setIcon(iconobuscar);
        //BOTON MODIFICAR
        ImageIcon icmodif = new ImageIcon(getClass().getResource("/Imagenes/edit.png"));
        Icon iconomodif = new ImageIcon(icmodif.getImage().getScaledInstance(25, 25, Image.SCALE_DEFAULT));
        btnModif.setIcon(iconomodif);
        //Deshabilitar botones
        btnAgregar.setEnabled(false);
        btnBuscarE.setEnabled(false);
        btnBuscar.setEnabled(false);
        btnModif.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlPrincipal = new javax.swing.JTabbedPane();
        pnlAltas = new javax.swing.JPanel();
        lblIdGen = new javax.swing.JLabel();
        lblAltRFC = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtAltIDG = new javax.swing.JTextField();
        txtAltNom = new javax.swing.JTextField();
        txtAltOy = new javax.swing.JTextField();
        pnlAv = new javax.swing.JPanel();
        lblAvisoIdGen = new javax.swing.JLabel();
        lblAvisoNombre = new javax.swing.JLabel();
        lblAvisoOy = new javax.swing.JLabel();
        lblAltOy = new javax.swing.JLabel();
        pnlBajas = new javax.swing.JPanel();
        lblBajID = new javax.swing.JLabel();
        txtBajID = new javax.swing.JTextField();
        btnBuscarE = new javax.swing.JButton();
        lblAvisoID2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClienteE = new javax.swing.JTable();
        btnEliminar1 = new javax.swing.JButton();
        pnlCambios = new javax.swing.JPanel();
        btnModif = new javax.swing.JButton();
        lblIdGen1 = new javax.swing.JLabel();
        lblCamNom = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtCamIDG = new javax.swing.JTextField();
        txtCamNom = new javax.swing.JTextField();
        txtCamNoy = new javax.swing.JTextField();
        lblAvisoIDG1 = new javax.swing.JLabel();
        lblCamOy = new javax.swing.JLabel();
        lblAvisoIdGenCam = new javax.swing.JLabel();
        lblAvisoOyCam = new javax.swing.JLabel();
        pnlAv1 = new javax.swing.JPanel();
        lblAvisoNombreCam = new javax.swing.JLabel();
        btnBuscarM = new javax.swing.JButton();
        pnlConsultas = new javax.swing.JPanel();
        lblConsIdCan = new javax.swing.JLabel();
        txtConIDGen = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblAvisoID3 = new javax.swing.JLabel();
        btnBuscarTds = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClienteC = new javax.swing.JTable();
        pnlReportes = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GENEROS");

        pnlPrincipal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        lblIdGen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdGen.setText("ID Genero:");

        lblAltRFC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltRFC.setText("Nombre");

        btnAgregar.setBackground(new java.awt.Color(255, 255, 255));
        btnAgregar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtAltIDG.setEditable(false);
        txtAltIDG.setText("0");
        txtAltIDG.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltIDG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltIDGKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltIDGKeyTyped(evt);
            }
        });

        txtAltNom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltNomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltNomKeyTyped(evt);
            }
        });

        txtAltOy.setEditable(false);
        txtAltOy.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtAltOy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAltOyActionPerformed(evt);
            }
        });
        txtAltOy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAltOyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAltOyKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtAltOy, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(txtAltIDG, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAltNom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtAltIDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltOy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAltNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lblAvisoIdGen.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIdGen.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoNombre.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoNombre.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoOy.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoOy.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlAvLayout = new javax.swing.GroupLayout(pnlAv);
        pnlAv.setLayout(pnlAvLayout);
        pnlAvLayout.setHorizontalGroup(
            pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvisoIdGen, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoOy, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAvLayout.setVerticalGroup(
            pnlAvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvLayout.createSequentialGroup()
                .addComponent(lblAvisoIdGen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAvisoOy, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAvisoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        lblAltOy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAltOy.setText("Oyentes");

        javax.swing.GroupLayout pnlAltasLayout = new javax.swing.GroupLayout(pnlAltas);
        pnlAltas.setLayout(pnlAltasLayout);
        pnlAltasLayout.setHorizontalGroup(
            pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAltRFC)
                    .addComponent(lblAltOy)
                    .addComponent(lblIdGen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(pnlAv, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAltasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(130, 130, 130))
        );
        pnlAltasLayout.setVerticalGroup(
            pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAltasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAltasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAltasLayout.createSequentialGroup()
                        .addComponent(lblIdGen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblAltOy)
                        .addGap(24, 24, 24)
                        .addComponent(lblAltRFC))
                    .addComponent(pnlAv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(82, 82, 82))
        );

        pnlPrincipal.addTab("ALTAS", pnlAltas);

        lblBajID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBajID.setText("ID Cancion:");

        txtBajID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtBajID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBajIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBajIDKeyTyped(evt);
            }
        });

        btnBuscarE.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarE.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarE.setText("BUSCAR");
        btnBuscarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEActionPerformed(evt);
            }
        });

        lblAvisoID2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoID2.setForeground(new java.awt.Color(255, 0, 0));

        tblClienteE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Email", "Contraseña", "Razon Social", "RFC", "Domicilio", "CDFI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblClienteE);

        btnEliminar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.setEnabled(false);
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBajasLayout = new javax.swing.GroupLayout(pnlBajas);
        pnlBajas.setLayout(pnlBajasLayout);
        pnlBajasLayout.setHorizontalGroup(
            pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBajasLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblBajID)
                .addGap(46, 46, 46)
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addComponent(btnBuscarE)
                        .addGap(70, 70, 70)
                        .addComponent(lblAvisoID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addComponent(txtBajID, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(528, 528, 528))
            .addGroup(pnlBajasLayout.createSequentialGroup()
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGap(459, 459, 459)
                        .addComponent(btnEliminar1))
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBajasLayout.setVerticalGroup(
            pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBajasLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBajID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBajID))
                .addGroup(pnlBajasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblAvisoID2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBajasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnEliminar1)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("BAJAS", pnlBajas);

        btnModif.setBackground(new java.awt.Color(255, 255, 255));
        btnModif.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnModif.setText("MODIFICAR");
        btnModif.setEnabled(false);
        btnModif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifActionPerformed(evt);
            }
        });

        lblIdGen1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIdGen1.setText("ID Genero:");

        lblCamNom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamNom.setText("Nombre");

        txtCamIDG.setEditable(false);
        txtCamIDG.setText("0");
        txtCamIDG.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamIDG.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamIDGKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamIDGKeyTyped(evt);
            }
        });

        txtCamNom.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamNomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamNomKeyTyped(evt);
            }
        });

        txtCamNoy.setEditable(false);
        txtCamNoy.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtCamNoy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCamNoyActionPerformed(evt);
            }
        });
        txtCamNoy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCamNoyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCamNoyKeyTyped(evt);
            }
        });

        lblAvisoIDG1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIDG1.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCamNom)
                    .addComponent(txtCamIDG, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtCamNoy))
                .addGap(18, 18, 18)
                .addComponent(lblAvisoIDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCamIDG, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoIDG1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(txtCamNoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCamNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblCamOy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCamOy.setText("Oyentes");

        lblAvisoIdGenCam.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoIdGenCam.setForeground(new java.awt.Color(255, 0, 0));

        lblAvisoOyCam.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoOyCam.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout pnlAv1Layout = new javax.swing.GroupLayout(pnlAv1);
        pnlAv1.setLayout(pnlAv1Layout);
        pnlAv1Layout.setHorizontalGroup(
            pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );
        pnlAv1Layout.setVerticalGroup(
            pnlAv1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 96, Short.MAX_VALUE)
        );

        lblAvisoNombreCam.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoNombreCam.setForeground(new java.awt.Color(255, 0, 0));

        btnBuscarM.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarM.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarM.setText("BUSCAR");
        btnBuscarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCambiosLayout = new javax.swing.GroupLayout(pnlCambios);
        pnlCambios.setLayout(pnlCambiosLayout);
        pnlCambiosLayout.setHorizontalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCamOy)
                    .addComponent(lblCamNom)
                    .addComponent(lblIdGen1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addComponent(lblAvisoIdGenCam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnBuscarM))
                    .addComponent(lblAvisoOyCam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoNombreCam, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlAv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCambiosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModif)
                .addGap(164, 164, 164))
        );
        pnlCambiosLayout.setVerticalGroup(
            pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCambiosLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addComponent(pnlAv1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(63, 63, 63))
                            .addComponent(btnBuscarM)
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addComponent(lblAvisoIdGenCam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAvisoOyCam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblAvisoNombreCam, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModif)
                        .addGap(103, 103, 103))
                    .addGroup(pnlCambiosLayout.createSequentialGroup()
                        .addGroup(pnlCambiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCambiosLayout.createSequentialGroup()
                                .addComponent(lblIdGen1)
                                .addGap(18, 18, 18)
                                .addComponent(lblCamOy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCamNom)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlPrincipal.addTab("CAMBIOS", pnlCambios);

        lblConsIdCan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblConsIdCan.setText("ID Generos:");

        txtConIDGen.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(221, 198, 164)));
        txtConIDGen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtConIDGenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtConIDGenKeyTyped(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblAvisoID3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblAvisoID3.setForeground(new java.awt.Color(255, 0, 0));

        btnBuscarTds.setBackground(new java.awt.Color(255, 255, 255));
        btnBuscarTds.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnBuscarTds.setText("MOSTRAR TODOS");
        btnBuscarTds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTdsActionPerformed(evt);
            }
        });

        tblClienteC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_genero", "no_oyentes", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblClienteC);

        javax.swing.GroupLayout pnlConsultasLayout = new javax.swing.GroupLayout(pnlConsultas);
        pnlConsultas.setLayout(pnlConsultasLayout);
        pnlConsultasLayout.setHorizontalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(lblConsIdCan)
                        .addGap(45, 45, 45)
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConIDGen, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlConsultasLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnBuscar)))
                        .addGap(73, 73, 73)
                        .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarTds)
                            .addComponent(lblAvisoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlConsultasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlConsultasLayout.setVerticalGroup(
            pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlConsultasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblConsIdCan)
                        .addComponent(txtConIDGen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblAvisoID3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlConsultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(btnBuscarTds))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("CONSULTAS", pnlConsultas);

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 577, Short.MAX_VALUE)
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        pnlPrincipal.addTab("REPORTES", pnlReportes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTdsActionPerformed
        Object generoC[] = new Object[2];
        DAOgeneros genero = new DAOgeneros();
        ArrayList<Generos> generos = null;
        while (c.getRowCount() > 0) {
            c.removeRow(0);
        }
        if (c.getRowCount() == 0) {
            try {
                generos = genero.select();
                for (Generos gen : generos) {

                    generoC[0] = gen.getId_genero();
                    generoC[1] = gen.getNo_oyentes();
                    generoC[2] = gen.getNombre_genero();

                    c.addRow(generoC);
                }
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
        }
        txtConIDGen.setText("");
    }//GEN-LAST:event_btnBuscarTdsActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        boolean encontrado = false;
        idBuscar = Integer.parseInt(txtConIDGen.getText());
        Object generoM[] = new Object[2];
        DAOgeneros genero = new DAOgeneros();
        ArrayList<Generos> generos = null;

        try {
            generos = genero.select();
            for (Generos gen : generos) {
                if (gen.getId_genero() == idBuscar) {

                    generoM[0] = gen.getId_genero();
                    generoM[1] = gen.getNo_oyentes();
                    generoM[2] = gen.getNombre_genero();

                    encontrado = true;
                    break;
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        if (encontrado) {
            while (c.getRowCount() > 0) {
                c.removeRow(0);
            }
            if (c.getRowCount() == 0) {
                c.addRow(generoM);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Genero no encontrado");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtConIDGenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConIDGenKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtConIDGenKeyTyped

    private void txtConIDGenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtConIDGenKeyReleased
        habilitarBotonB();
        validarVacios3();
    }//GEN-LAST:event_txtConIDGenKeyReleased

    private void btnBuscarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMActionPerformed
        boolean generoEncontrado = false;
        idModificar = Integer.parseInt(txtCamIDG.getText());
        Object generoM[] = new Object[2];
        DAOgeneros genero = new DAOgeneros();
        ArrayList<Generos> generos = null;

        try {
            generos = genero.select();
            for (Generos gen : generos) {
                if (gen.getId_genero() == idModificar) {
                    generoM[0] = gen.getId_genero();
                    generoM[1] = gen.getNo_oyentes();
                    generoM[2] = gen.getNombre_genero();

                    generoEncontrado = true;
                    break;
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        if (generoEncontrado) {
            btnModif.setEnabled(true);
            habilitarCompMod();
            agrgarElementosModif(generoM);
        } else
            JOptionPane.showMessageDialog(this, "Genero no encontrado");
    }//GEN-LAST:event_btnBuscarMActionPerformed

    private void btnModifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifActionPerformed
        //Validar los INT o hacer la conversion del texto a entero.
        generoModID = Integer.parseInt(txtCamIDG.getText());
        int generoModNo_oyentes = Integer.parseInt(txtCamNoy.getText());
        String generoModNombre_genero = txtCamNom.getText();

        DAOgeneros genero = new DAOgeneros();
        Generos generoU = new Generos();
        generoU.setId_genero(generoModID);
        generoU.setNo_oyentes(generoModNo_oyentes);
        generoU.setNombre_genero(generoModNombre_genero);

        try {
            if (genero.update(generoU) != 0) {
                JOptionPane.showMessageDialog(this, "Genero modificado con exito");
                deshabilitarCompMod();
            } else {
                JOptionPane.showMessageDialog(this, "El genero no se modifico");
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }//GEN-LAST:event_btnModifActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed

        if (idEliminar != 0) {
            DAOgeneros genero = new DAOgeneros();
            Generos deleteGenero = new Generos();
            deleteGenero.setId_genero(idEliminar);
            try {
                if (genero.delete(deleteGenero) != 0) {
                    JOptionPane.showMessageDialog(this, "Genero eliminado con exito");
                    txtBajID.setText("");
                    txtBajID.removeAll();
                } else {
                    JOptionPane.showMessageDialog(this, "Hubo un error al eliminar el genero");
                }
            } catch (SQLException ex) {
                ex.printStackTrace(System.out);
            }
        }
        while (e.getRowCount() > 0) {
            e.removeRow(0);
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnBuscarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEActionPerformed
        boolean generoEncontrado = false;
        idEliminar = Integer.parseInt(txtBajID.getText());
        Object generoE[] = new Object[2];
        DAOgeneros genero = new DAOgeneros();
        ArrayList<Generos> geneross = null;

        try {
            geneross = genero.select();
            for (Generos gen : geneross) {
                if (gen.getId_genero() == idEliminar) {
                    generoE[0] = gen.getId_genero();
                    generoE[1] = gen.getNo_oyentes();
                    generoE[2] = gen.getNombre_genero();
                    generoEncontrado = true;
                    break;
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
        while (e.getRowCount() > 0) {
            e.removeRow(0);
        }
        if (generoEncontrado) {

            if (e.getRowCount() == 0) {
                e.addRow(generoE);
                btnEliminar1.setEnabled(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Genero no encontrado");
        }
    }//GEN-LAST:event_btnBuscarEActionPerformed

    private void txtBajIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBajIDKeyTyped
        validarNumeros(evt);
    }//GEN-LAST:event_txtBajIDKeyTyped

    private void txtBajIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBajIDKeyReleased
        habilitarBotonE();
        validarVacios2();
    }//GEN-LAST:event_txtBajIDKeyReleased

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int generoModId = Integer.parseInt(txtAltIDG.getText());
        int generoModNo_oyentes = Integer.parseInt(txtAltOy.getText());
        String generoModNombre_genero = txtAltNom.getText();

        //        emailCliente,passwordCliente,rsCliente,rfcCLiente,domicilioCliente,cdfiCliente
        insertarGenero(generoModId, generoModNo_oyentes, generoModNombre_genero);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtAltNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltNomKeyTyped
         validarNumeros(evt);
    }//GEN-LAST:event_txtAltNomKeyTyped

    private void txtAltNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltNomKeyReleased
         habilitarBoton();
        validarVacios();
    }//GEN-LAST:event_txtAltNomKeyReleased

    private void txtAltIDGKeyReleased(java.awt.event.KeyEvent evt) {
         validarNumeros(evt);
    }
    private void txtAltIDGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltIDGKeyTyped
         validarNumeros(evt);
    }//GEN-LAST:event_txtAltIDGKeyTyped

//GEN-FIRST:event_txtAltIDCKeyReleased
 
//GEN-LAST:event_txtAltIDCKeyReleased

    private void txtAltOyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAltOyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltOyActionPerformed

    private void txtAltOyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltOyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltOyKeyReleased

    private void txtAltOyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAltOyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAltOyKeyTyped

    private void txtCamIDGKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDGKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamIDGKeyReleased

    private void txtCamIDGKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamIDGKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamIDGKeyTyped

    private void txtCamNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamNomKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamNomKeyReleased

    private void txtCamNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamNomKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamNomKeyTyped

    private void txtCamNoyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCamNoyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamNoyActionPerformed

    private void txtCamNoyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamNoyKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamNoyKeyReleased

    private void txtCamNoyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCamNoyKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCamNoyKeyTyped

    public void validarVacios() {
        if (txtAltIDG.getText().isEmpty()) {
            lblAvisoIdGen.setText("Campo obligatorio");
        } else {
            lblAvisoIdGen.setText("");
        }
        if (lblAvisoOy.getText().isEmpty()) {
            lblAvisoOy.setText("Campo obligatorio");
        } else {
            lblAvisoOy.setText("");
        }
        if (txtAltNom.getText().isEmpty()) {
            lblAvisoNombre.setText("Campo obligatorio");
        } else {
            lblAvisoNombre.setText("");
        }

        /*if(txtAltCorrC.getText().isEmpty()){
            lblAvisoCorr.setText("Campo obligatorio");
        }else 
            if(!txtAltCorrC.getText().contains("@")
                  ||!txtAltCorrC.getText().contains(".")){
                lblAvisoCorr.setText("Correo NO valido");
            }else{
                lblAvisoCorr.setText("");
            }*/
    }

    public void validarVacios1() {
        if (txtCamIDG.getText().isEmpty()) {
            lblAvisoIdGenCam.setText("Campo obligatorio");
        } else {
            lblAvisoIdGenCam.setText("");
        }
        if (txtCamNoy.getText().isEmpty()) {
            lblAvisoOyCam.setText("Campo obligatorio");
        } else {
            lblAvisoOyCam.setText("");
        }
        if (txtCamNom.getText().isEmpty()) {
            lblAvisoNombreCam.setText("Campo obligatorio");
        } else {
            lblAvisoNombreCam.setText("");
        }

    }

    public void validarVacios2() {
        if (txtBajID.getText().isEmpty()) {
            lblAvisoID2.setText("ID obligatorio");
        } else {
            lblAvisoID2.setText("");
        }
    }

    public void validarVacios3() {
        if (txtConIDGen.getText().isEmpty()) {
            lblAvisoID3.setText("ID obligatorio");
        } else {
            lblAvisoID3.setText("");
        }
    }

    public void validarID(java.awt.event.KeyEvent evento) {
        if (evento.getKeyChar() >= 33 && evento.getKeyChar() <= 47
                || evento.getKeyChar() >= 58 && evento.getKeyChar() <= 64
                || evento.getKeyChar() >= 91 && evento.getKeyChar() <= 255) {
            evento.consume();
            JOptionPane.showMessageDialog(this, "Solo se permiten numeros y mayusculas");
        }
    }

    public void validarNumeros(java.awt.event.KeyEvent evento) {
        if (evento.getKeyChar() >= 32 && evento.getKeyChar() <= 47
                || evento.getKeyChar() >= 58 && evento.getKeyChar() <= 255) {
            evento.consume();
            JOptionPane.showMessageDialog(this, "Solo Numeros");
        }
    }

    public void habilitarBoton() {
        if (txtAltIDG.getText().isEmpty()
                || txtAltOy.getText().isEmpty()
                || txtAltNom.getText().isEmpty()) {
            btnAgregar.setEnabled(false);
        } else {
            btnAgregar.setEnabled(true);
        }
    }

    public void habilitarBotonM() {
        if (txtAltIDG.getText().isEmpty()
                || txtAltOy.getText().isEmpty()
                || txtAltNom.getText().isEmpty()) {
            btnModif.setEnabled(false);
        } else {
            btnModif.setEnabled(true);
        }
    }

    public void habilitarBotonE() {
        if (txtBajID.getText().isEmpty()) {
            btnBuscarE.setEnabled(false);
        } else {
            btnBuscarE.setEnabled(true);
        }
    }

    public void habilitarBotonB() {
        if (txtConIDGen.getText().isEmpty()) {
            btnBuscar.setEnabled(false);
        } else {
            btnBuscar.setEnabled(true);
        }
    }

    public void validarCaracter(java.awt.event.KeyEvent evento) {
        if (evento.getKeyChar() >= 33 && evento.getKeyChar() <= 64
                || evento.getKeyChar() >= 91 && evento.getKeyChar() <= 96
                || evento.getKeyChar() >= 123 && evento.getKeyChar() <= 208
                || evento.getKeyChar() >= 210 && evento.getKeyChar() <= 240
                || evento.getKeyChar() >= 242 && evento.getKeyChar() <= 255) {
            evento.consume();
            JOptionPane.showMessageDialog(this, "No se permiten caracteres especiales");
        }
    }

    private void insertarGenero(int id_genero, int no_oyentes, String nombre_genero) {

        DAOgeneros nuevoGenero = new DAOgeneros();
        Generos genero = new Generos(id_genero, no_oyentes, nombre_genero);
        try {
            if (nuevoGenero.insert(genero) != 0) {
                JOptionPane.showMessageDialog(this, "Genero dado de alta con exito");
            } else {
                JOptionPane.showMessageDialog(this, "El genero no pudo ser dado de alta");
            }
        } catch (SQLException ex) {
            ex.printStackTrace(System.out);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarE;
    private javax.swing.JButton btnBuscarM;
    private javax.swing.JButton btnBuscarTds;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnModif;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblAltOy;
    private javax.swing.JLabel lblAltRFC;
    private javax.swing.JLabel lblAvisoID2;
    private javax.swing.JLabel lblAvisoID3;
    private javax.swing.JLabel lblAvisoIDG1;
    private javax.swing.JLabel lblAvisoIdGen;
    private javax.swing.JLabel lblAvisoIdGenCam;
    private javax.swing.JLabel lblAvisoNombre;
    private javax.swing.JLabel lblAvisoNombreCam;
    private javax.swing.JLabel lblAvisoOy;
    private javax.swing.JLabel lblAvisoOyCam;
    private javax.swing.JLabel lblBajID;
    private javax.swing.JLabel lblCamNom;
    private javax.swing.JLabel lblCamOy;
    private javax.swing.JLabel lblConsIdCan;
    private javax.swing.JLabel lblIdGen;
    private javax.swing.JLabel lblIdGen1;
    private javax.swing.JPanel pnlAltas;
    private javax.swing.JPanel pnlAv;
    private javax.swing.JPanel pnlAv1;
    private javax.swing.JPanel pnlBajas;
    private javax.swing.JPanel pnlCambios;
    private javax.swing.JPanel pnlConsultas;
    private javax.swing.JTabbedPane pnlPrincipal;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JTable tblClienteC;
    private javax.swing.JTable tblClienteE;
    private javax.swing.JTextField txtAltIDG;
    private javax.swing.JTextField txtAltNom;
    private javax.swing.JTextField txtAltOy;
    private javax.swing.JTextField txtBajID;
    private javax.swing.JTextField txtCamIDG;
    private javax.swing.JTextField txtCamNom;
    private javax.swing.JTextField txtCamNoy;
    private javax.swing.JTextField txtConIDGen;
    // End of variables declaration//GEN-END:variables
    private int idEliminar = 0, idModificar = 0, generoModID = 0, idBuscar = 0;

    private void agrgarElementosModif(Object[] generoM) {
//        emailCliente,passwordCliente,rsCliente,rfcCLiente,domicilioCliente,cdfiCliente
        txtCamIDG.setText(generoM[0].toString());
        txtCamNoy.setText(generoM[1].toString());
        txtCamNom.setText(generoM[2].toString());
    }

    private void habilitarCompMod() {
        txtCamIDG.setEditable(true);
        txtCamNoy.setEditable(true);
        txtCamNom.setEditable(true);
    }

    private void deshabilitarCompMod() {
        txtCamIDG.setEditable(false);
        txtCamNoy.setEditable(false);
        txtCamNom.setEditable(false);
    }
}
